/* GENERATED FILE - do not edit.
 * Source: index.html, regenerated by tools/sync-ask-core.mjs.
 *
 * The shared Ask CJHQ deterministic engine. One implementation, two callers:
 * the CJHQ website runs this code inline, the external WhatsApp bridge imports
 * this module. There is no second copy of the handlers and no second language
 * detector.
 *
 * BROWSER-FREE BY CONSTRUCTION. The browser AI adapter is fenced off in
 * index.html and stripped here, so this module references no window, document,
 * Firebase, Firestore, App Check, gstatic import or browser storage. It is
 * stateless: no conversation history, no user identity, nothing that could
 * carry one caller's context into another's answer.
 *
 * HANDLER ORDER IS PART OF THE CONTRACT
 *   askHalachic -> askEruv -> askEmergency -> askZmanim -> askCalendar
 *   -> askCommunityDirectory -> askCjhqResources -> AI only where permitted
 * askHalachic runs first and stays authoritative: it calls the practical
 * handlers itself to attach what CJHQ actually knows beneath the referral to a
 * rov, so a caller cannot route around it.
 *
 * FOR THE BRIDGE
 *   import { askAnswer } from './ask-core.mjs';
 *   const res = await askAnswer({ text: incomingWhatsAppMessage });
 * Pass the raw message. Do not pre-translate or normalise it - askDetectLanguage
 * needs the original characters to tell Yiddish from Hebrew. Omit aiAdapter and
 * the deterministic path runs alone, which is what v1 wants.
 */
import { categories } from './ask-data.mjs';

function cjhqNormalizeSearch(str){
  return String(str == null ? '' : str)
    .toLowerCase()
    .replace(/\u2019/g, "'")      // curly apostrophe (phone keyboards) -> straight
    .replace(/'s\b/g, '')         // possessive: "driver's license" -> "driver license",
                                  // so it matches the stored "Driver License"
    .replace(/licence/g, 'license'); // Canadian/British spelling -> the stored spelling
}

/* ================= ASK CJHQ =================
   Admin-only assistant. Not public: this code ships in every route file, but
   the interface that calls it exists only in tools/admin-panel.html, which is
   injected into admin.html alone. No credential exists anywhere in this file.

   Gemini (Firebase AI Logic, Developer API) is wired as a PHRASING layer only.
   Facts always come from the structured handlers or the CJHQ resource index
   first; if the model is unavailable the deterministic answer is what shows.

   Languages: English, French, Hebrew and Yiddish. Yiddish is a first-class
   language here, not a variant of Hebrew, and is never answered in Hebrew.

   Architecture:
     askRun(question, opts, aiAdapter)  - the shared engine
       -> askHalachic (first, and authoritative)
       -> askEruv, askEmergency, askZmanim, askCalendar,
          askCommunityDirectory, askCjhqResources
       -> the injected AI adapter, only to phrase an answer that already exists
     askAnswer({ text })                - public entry point for a non-browser
                                          caller; returns the user-facing fields
                                          only, no diagnostics
     askCommunityAssistant(question, opts) - the browser wrapper, which supplies
                                          ASK_BROWSER_AI

   The AI layer is injected rather than read from file scope, so this code runs
   unchanged in a browser and in Node. tools/sync-ask-core.mjs generates
   ask-core.mjs from this region for the external WhatsApp bridge; run its
   --check after every edit here or the two will drift.                        */

const ASK_ASSISTANT_NAME = 'Ask CJHQ';
const ASK_ASSISTANT_SUB  = 'Your Jewish Community Assistant';

/* ---- Model / provider configuration ----
   Switching model or provider is these three lines and nothing else. The
   frontend never holds a key: AI_GATEWAY_URL points at the CJHQ-controlled
   gateway, which holds the credential and forwards to whichever OpenAI-
   compatible endpoint is configured there.

   Because every candidate model is served behind an OpenAI-compatible API,
   moving between Qwen, Gemma, Mistral, DeepSeek, or a self-hosted Ollama box
   is a value change here plus one variable in the gateway. No code rewrite. */
/* Firebase AI Logic, Gemini Developer API, on the Spark plan.

   There is NO API key here and none is needed: with the Developer API the key
   lives in Google's proxy, and the browser authenticates via App Check. Do not
   add a Gemini key to this file - it would be public within one deploy.

   Model choice: gemini-3.5-flash-lite gives 15 RPM / 500 RPD on the free tier,
   against 5 RPM / 20 RPD for the full Flash models. Twenty requests a day is
   not enough to test with, let alone serve the community - that limit, not the
   free tier itself, is what produced the earlier 429s. */


/* Default source registry. Seeded into Firestore on request so CJHQ can edit
   it without a code change; used read-only if Firestore is unavailable. */
const ASK_DEFAULT_SOURCES = [
  { id:'cjhq-resources', name:'CJHQ Resource Centre', url:'https://cjhq.org/resources',
    type:'CJHQ', description:'The 63 government and community resources maintained by CJHQ.',
    active:true, authoritative:true, timeSensitive:false, updateFrequency:'monthly',
    lastChecked:'', lastIndexed:'', integration:'connected', notes:'Indexed directly from the site, no external call needed.' },
  { id:'cjhq-tools', name:'CJHQ Tools', url:'https://cjhq.org/child-travel-consent',
    type:'CJHQ', description:'CJHQ-built tools such as the Child Travel Consent Letter.',
    active:true, authoritative:true, timeSensitive:false, updateFrequency:'as needed',
    lastChecked:'', lastIndexed:'', integration:'connected', notes:'' },
  { id:'hebcal-calendar', name:'Hebcal — Jewish Calendar', url:'https://www.hebcal.com/',
    type:'Calendar', description:'Hebrew dates and holiday dates.',
    active:true, authoritative:true, timeSensitive:false, updateFrequency:'live',
    lastChecked:'', lastIndexed:'', integration:'pending', notes:'Public JSON API, no credential required. Wire in Phase 2.' },
  { id:'hebcal-zmanim', name:'Hebcal — Montreal Zmanim', url:'https://www.hebcal.com/zmanim?geonameid=6077243',
    type:'Zmanim', description:'Daily zmanim for Montreal.',
    active:true, authoritative:true, timeSensitive:true, updateFrequency:'live',
    lastChecked:'', lastIndexed:'', integration:'pending', notes:'Times must never be calculated or guessed by an LLM.' },
  { id:'montreal-eruv', name:'Montreal Eruv', url:'https://montrealeruv.ca/',
    type:'Eruv', description:'Official Montreal Eruv status and map.',
    active:true, authoritative:true, timeSensitive:true, updateFrequency:'weekly',
    lastChecked:'', lastIndexed:'', integration:'link-only', notes:'Status is never cached. Users are sent to the official page.' },
  { id:'hatzolah-montreal', name:'Hatzolah Montreal', url:'https://www.hatzolahmontreal.com/',
    type:'Emergency', description:'Volunteer emergency medical service.',
    active:true, authoritative:true, timeSensitive:false, updateFrequency:'as needed',
    lastChecked:'', lastIndexed:'', integration:'link-only', notes:'Never state a phone number that is not verified from the official site.' },
  { id:'findmtl', name:'FindMTL', url:'https://findmtl.ca/',
    type:'FindMTL', description:'Montreal Jewish community directory: shuls, kosher food, organisations.',
    active:false, authoritative:false, timeSensitive:false, updateFrequency:'unknown',
    lastChecked:'', lastIndexed:'', integration:'pending', notes:'Returns 403 to automated requests. Do not scrape. Needs permission or an API before use.' },
  { id:'canada-gov', name:'Government of Canada', url:'https://www.canada.ca/',
    type:'Government', description:'Official federal guidance on travel, passports and border crossing.',
    active:true, authoritative:true, timeSensitive:false, updateFrequency:'as needed',
    lastChecked:'', lastIndexed:'', integration:'link-only', notes:'' }
];

const ASK_SOURCE_TYPES = ['CJHQ','Government','Jewish Organization','FindMTL','Community','Zmanim','Eruv','Emergency','Calendar','Other'];

/* ---------- structured service records (spec sections 7, 11, 13) ----------
   These hold FACTS ABOUT SOURCES, never the volatile values themselves. The
   Eruv record deliberately has no "status" field: storing "the eruv is up"
   would be wrong within a week. Phone numbers are left empty rather than
   guessed - an invented emergency number is the worst failure this system
   could produce.                                                              */
const ASK_ERUV_RECORD = {
  id:'montreal-eruv',
  organization:'Montreal Eruv',
  website:'https://montrealeruv.ca/',
  statusPage:'https://montrealeruv.ca/',
  mapUrl:'https://montrealeruv.ca/',
  serviceArea:'Montreal',
  source:'montrealeruv.ca',
  lastVerified:'',          // set when a human confirms the links
  timeSensitive:true,       // status must always be fetched, never stored
  statusPolicy:'never-cache'
};

const ASK_HATZOLAH_RECORD = {
  id:'hatzolah-montreal',
  organization:'Hatzolah Montreal',
  emergencyNumbers:[],      // EMPTY BY DESIGN - never invent an emergency number
  website:'https://www.hatzolahmontreal.com/',
  mapUrl:'',
  serviceArea:'Montreal',
  source:'hatzolahmontreal.com',
  lastVerified:'',
  timeSensitive:false,
  note:'Numbers must be entered by an admin from the official site, or fetched live.'
};

/* Spec section 13: when several sources could answer, this is the order. Lower
   number wins. Used to sort sources on an answer so the admin can see which
   source was preferred and why. */
const ASK_SOURCE_PRIORITY = {
  'CJHQ':1, 'Government':2, 'Jewish Organization':3, 'Zmanim':3, 'Eruv':3,
  'Emergency':3, 'Calendar':3, 'FindMTL':4, 'Community':5, 'Other':6
};
function askSortSources(list){
  return (list || []).slice().sort((a,b)=>
    (ASK_SOURCE_PRIORITY[a.type] || 9) - (ASK_SOURCE_PRIORITY[b.type] || 9));
}

/* ---------- location (spec section 12) ----------
   Montreal unless the question names somewhere else. Nothing about the user's
   actual position is requested, derived or stored - only what they typed.     */
const ASK_DEFAULT_LOCATION = { name:'Montreal', geonameid:6077243 };
const ASK_KNOWN_LOCATIONS = [
  { match:/\bmontr[e\u00e9]al\b|\u05de\u05d0[\u0591-\u05C7]?\u05e0\u05d8\u05e8\u05e2\u05d0[\u0591-\u05C7]?\u05dc|\u05de\u05d0\u05e0\u05d8\u05e8\u05d9\u05d0\u05dc|\u05de\u05d5\u05e0\u05d8\u05e8\u05d9\u05d0\u05d5\u05dc/i, name:'Montreal',  geonameid:6077243 },
  { match:/\bbrooklyn\b/i,                         name:'Brooklyn',  geonameid:5110302 },
  { match:/\b(new york|nyc|manhattan)\b/i,          name:'New York',  geonameid:5128581 },
  { match:/\bmonsey\b/i,                            name:'Monsey',    geonameid:5128238 },
  { match:/\blakewood\b/i,                          name:'Lakewood',  geonameid:5100280 },
  { match:/\btoronto\b/i,                           name:'Toronto',   geonameid:6167865 },
  { match:/\b(jerusalem|yerushalayim|\u05d9\u05e8\u05d5\u05e9\u05dc\u05d9\u05dd)\b/i, name:'Jerusalem', geonameid:281184 }
];
function askDetectLocation(q){
  const s = String(q || '');
  for(const loc of ASK_KNOWN_LOCATIONS){
    if(loc.match.test(s)) return { name:loc.name, geonameid:loc.geonameid, explicit:true };
  }
  return { name:ASK_DEFAULT_LOCATION.name, geonameid:ASK_DEFAULT_LOCATION.geonameid, explicit:false };
}

/* ---------- community directory registry ----------
   Structure only. CJHQ has no verified shul / mikvah / kosher data yet, so this
   ships EMPTY and nothing is invented to fill it. Entries are added by an admin
   or, later, by a directory integration.

   Entry shape:
     { id, type:'shul'|'mikvah'|'kosher'|'minyan', name, address, neighbourhood,
       phone, url, hours, source, verified:boolean, lastUpdated:'YYYY-MM-DD',
       active:boolean }

   verified and lastUpdated exist because this is exactly the kind of data that
   goes stale and misleads. An unverified mikvah time is worse than none.       */
let askDirectoryEntries = [];
const ASK_DIRECTORY_TYPES = ['shul','mikvah','kosher','minyan'];

/* ---------- CJHQ resource matcher ----------
   Pure client-side scoring over the resource index already on the page. No AI
   and no network call, so it works today and the AI layer can call it later. */
// How many resource titles contain this word. Cached because it is stable for
// the life of the page and called once per word per resource.
let __askTitleFreq = null;
function askTitleFrequency(word){
  if(!__askTitleFreq){
    __askTitleFreq = Object.create(null);
    (typeof categories !== 'undefined' ? categories : []).forEach(cat=>{
      (cat.groups || []).forEach(g=>{
        (g.items || []).forEach(it=>{
          const seen = new Set(
            cjhqNormalizeSearch((String(it.en || '') + ' ' + String(it.fr || '')).toLowerCase())
              .split(/\s+/).filter(Boolean));
          seen.forEach(w => { __askTitleFreq[w] = (__askTitleFreq[w] || 0) + 1; });
        });
      });
    });
  }
  return __askTitleFreq[word] || 0;
}

/* ---------- Hebrew/Yiddish term bridge ----------
   The resource matcher scores on [a-z0-9] only, so a question written in
   Hebrew or Yiddish script produced no words at all and matched nothing - the
   same passport question answered in English and failed in Hebrew.

   This maps script and transliterated terms onto the English keyword the
   resource index already uses. It adds no resources and no facts: it only lets
   a Yiddish or Hebrew question reach the SAME CJHQ resource an English one
   reaches, which is what section 11 requires. */
const ASK_TERM_BRIDGE = [
  [/\u05e4\u05d0\u05e1\u05e4\u05d0\u05e8\u05d8|\u05e4\u05e2\u05e1\u05e4\u05d0\u05e8\u05d8|\u05d3\u05e8\u05db\u05d5\u05df|paspart/i, 'passport'],
  [/\u05e0\u05e2\u05e7\u05e1\u05d5\u05e1/i,                                   'nexus'],
  [/\u05d5\u05d5\u05d9\u05d6\u05e2|\u05d5\u05d9\u05d6\u05d4/i,                                 'visa'],
  [/\u05e8\u05d9\u05d9\u05d6|\u05e8\u05d9\u05d9\u05d6\u05df|\u05e0\u05e1\u05d9\u05e2\u05d4|\u05e0\u05e1\u05d9\u05e2\u05d5\u05ea|\u05d2\u05e8\u05e2\u05e0\u05d9\u05e5/i,                'travel border'],
  [/\u05e4\u05d0\u05e8\u05e7\u05df|\u05e4\u05d0\u05e8\u05e7\u05d9\u05e0\u05d2|\u05d7\u05e0\u05d9\u05d4/i,                          'parking permit'],
  [/\u05e9\u05e0\u05d9\u05d9|\u05e9\u05e0\u05d9\u05d9\u05e2\u05df|\u05e9\u05dc\u05d2/i,                                'snow removal'],
  [/\u05e7\u05d9\u05e0\u05d3|\u05e7\u05d9\u05e0\u05d3\u05e2\u05e8|\u05d9\u05dc\u05d3|\u05d9\u05dc\u05d3\u05d9\u05dd/i,                            'child'],
  [/\u05d2\u05e2\u05d1\u05d5\u05e8\u05d8\u05e1|\u05dc\u05d9\u05d3\u05d4/i,                                 'birth certificate'],
  [/\u05e8\u05d0\u05de\u05e7|\u05e8\u05e2\u05d2\u05d9\u05e2|\u05e7\u05e8\u05d0\u05e0\u05e7\u05df|\u05d1\u05e8\u05d9\u05d0\u05d5\u05ea/i,                        'ramq health insurance'],
  [/\u05d3\u05e8\u05d9\u05d9\u05d5\u05d5\u05e2\u05e8|\u05e4\u05d9\u05e8\u05e2\u05e8\u05e9\u05d9\u05d9\u05df|\u05e0\u05d4\u05d9\u05d2\u05d4/i,                        'driver license'],
  [/\u05d1\u05d9\u05e8\u05d2\u05e2\u05e8\u05e9\u05d0\u05e4\u05d8|\u05d0\u05d6\u05e8\u05d7\u05d5\u05ea/i,                           'citizenship'],
  [/\u05d0\u05d9\u05de\u05d9\u05d2\u05e8\u05d0\u05e6\u05d9\u05e2|\u05d4\u05d2\u05d9\u05e8\u05d4/i,                             'immigration'],
  [/\u05e9\u05d8\u05d9\u05d9\u05e2\u05e8\u05df|\u05de\u05e1\u05d9\u05dd/i,                                 'taxes']
];
function askBridgeTerms(question){
  const s = String(question || '');
  const add = [];
  ASK_TERM_BRIDGE.forEach(pair => { if(pair[0].test(s)) add.push(pair[1]); });
  return add.join(' ');
}

function askMatchResources(question, limit){
  // The bridge only ever appends English keywords; the original question is
  // left intact, so English and French matching is byte-for-byte unchanged.
  const bridged = String(question || '') + ' ' + askBridgeTerms(question);
  const q = cjhqNormalizeSearch(bridged.toLowerCase());
  if(q.length < 2) return [];
  // Common words appear in nearly every description, so two of them together
  // were enough to fake a match - "what is the capital of Peru" scored on
  // "what" and "the" alone. Strip them before scoring.
  const STOP = new Set(['the','and','for','you','your','can','how','where','when','with','from',
    'are','this','that','need','get','find','about','does','any','has','have','what','who','why',
    'was','were','will','would','should','could','there','their','they','been','into','than','then',
    'them','some','more','most','also','just','like','want','looking','know','tell','please','info',
    'information','help','question','anything','something',
    // French equivalents - a French question deserves the same filtering.
    'les','des','une','pour','dans','avec','sur','est','sont','que','qui','quoi','comment','puis',
    'peux','peut','vous','nous','mon','mes','mon','notre','avoir','faire','besoin','trouver','obtenir',
    'demander','cette','cet','ceci','cela','plus','tout','tous','toute','ainsi','aussi','renseignement',
    'renseignements','aide','ou']);
  // Transliterated Yiddish function words, for the same reason as the English
  // and French entries above: "vu ken ikh find passport information?" is a
  // passport question, but "ken" and "ikh" inflated the word count and pushed
  // coverage below the threshold, so it matched nothing.
  //
  // Applied ONLY when the question is actually Yiddish. Folding these into the
  // shared list changed an English answer - "How far is the airport from
  // Outremont?" stopped being a refusal and started matching a parking
  // resource, because "far" was no longer counted. English and French matching
  // has to stay exactly as it was.
  const YI_STOP = new Set(['ken','ikh','vu','vos','ver','ven','darf','vil','visn','wissen',
    'nisht','azoy','haynt','morgn','farvos','vifl','rufn','rufen','bakumen','betn','zukhn',
    'iz','zenen','zayn','kenen','oykh','epes','shoyn','undz','aykh','gefinen','far','mit',
    'dos','der','mir','tsu','ober','nit','veln']);
  const isYi = askDetectLanguage(question) === 'yi';
  // French elides constantly - "j'ai", "d'information", "l'enfant". Stripping the
  // apostrophe glued them into "jai" and "dinformation", which no stopword list
  // catches, so they inflated the word count and pushed real matches below the
  // coverage threshold. Split on the apostrophe first.
  const words = q.replace(/[\u2019']/g, ' ').split(/\s+/)
    .map(w => w.replace(/[^a-z0-9]/g,''))
    .filter(w => w.length > 2 && !STOP.has(w) && !(isYi && YI_STOP.has(w)));
  if(!words.length) return [];
  const out = [];
  (typeof categories !== 'undefined' ? categories : []).forEach(cat=>{
    (cat.groups || []).forEach(g=>{
      (g.items || []).forEach(it=>{
        const hay = cjhqNormalizeSearch([
          it.en, it.fr, it.what_en, it.need_en, it.steps_en,
          it.question_en, it.answer_en, (it.tips_list_en || []).join(' '),
          cat.en, g.heading_en || ''
        ].filter(Boolean).join(' ').toLowerCase());
        // Both titles count. Previously only the English title did, so a French
        // question ("Ou puis-je demander un passeport?") scored a single body hit
        // and fell below the relevance threshold - it matched nothing at all.
        const title = cjhqNormalizeSearch((String(it.en || '') + ' ' + String(it.fr || '')).toLowerCase());
        let score = 0, titleHits = 0, bodyHits = 0;
        words.forEach(w=>{
          if(title.includes(w)){ score += 10; titleHits++; }
          else if(hay.includes(w)){ score += 2; bodyHits++; }
        });
        if(title === q) score += 40;
        // Frequency turned out to be the wrong signal: "passport" appears in 10
        // titles but is exactly what the user means, while "times" appears in
        // only 2 and still produced a nonsense match for "minyan times at my
        // shul". What separates them is COVERAGE - how much of the question the
        // match actually explains. One matched word out of four is a coincidence;
        // one out of one is the question.
        const matched = titleHits + bodyHits;
        const coverage = matched / words.length;
        const relevant = (titleHits > 0 && (words.length <= 2 || coverage >= 0.5))
                       || bodyHits >= 2;
        if(relevant && score > 0) out.push({ score, item: it, category: cat.en });
      });
    });
  });
  out.sort((a,b)=> b.score - a.score);
  return out.slice(0, limit || 3);
}

/* ---------- structured handlers ----------
   Each returns the shared answer shape, or null if it does not apply. Answers
   here are either verifiable links or clearly-labelled "check the source"
   responses - none of them assert a time-sensitive fact from memory. */

/* ---------- language detection ----------
   Decides the language of the QUESTION, which is not the same as the site
   toggle: a French-speaking visitor may still type in English, and Hebrew
   speakers frequently type transliterated Hebrew inside an English sentence.

   Four languages: en, fr, he, yi. Hebrew and Yiddish share the same Unicode
   block, so script alone cannot separate them - a scored comparison does.
   Yiddish is NOT a dialect of Hebrew here and is never answered in Hebrew.

   Deliberately conservative: on a tie the answer is Hebrew, because Hebrew was
   the previous behaviour for all Hebrew-script input and a wrong switch to
   Yiddish is more jarring to a Hebrew speaker than the reverse.              */

/* Words that are Yiddish and not Hebrew. Weight 2 unless noted. Kept as a
   plain list so a Yiddish speaker can extend it without reading the code. */
const ASK_YI_WORDS = [
  // question words and pronouns
  '\u05d5\u05d5\u05d0\u05e1','\u05d5\u05d5\u05d0\u05b8\u05e1','\u05d5\u05d5\u05e2\u05e8','\u05d5\u05d5\u05d9','\u05d5\u05d5\u05d0\u05d5','\u05d5\u05d5\u05e2\u05df','\u05e4\u05d0\u05e8\u05d5\u05d5\u05d0\u05e1','\u05e4\u05d0\u05e8\u05d5\u05d5\u05d0\u05b8\u05e1','\u05d5\u05d5\u05d9\u05e4\u05dc',
  '\u05d0\u05d9\u05e8','\u05de\u05d9\u05e8','\u05d0\u05d5\u05e0\u05d6','\u05d0\u05d5\u05e0\u05d3\u05d6','\u05d6\u05d9\u05d9','\u05de\u05d9\u05d9\u05df','\u05de\u05d9\u05d9\u05e0\u05e2','\u05d0\u05d9\u05d9\u05e2\u05e8','\u05d6\u05d9\u05d9\u05df','\u05de\u05e2\u05df',
  // verbs and modals
  '\u05e7\u05e2\u05df','\u05e7\u05e2\u05e0\u05e2\u05df','\u05d5\u05d5\u05d9\u05dc','\u05d5\u05d5\u05e2\u05dc','\u05d3\u05d0\u05e8\u05e3','\u05d3\u05d0\u05b7\u05e8\u05e3','\u05d4\u05d0\u05d1','\u05d4\u05d0\u05d1\u05df','\u05d0\u05d9\u05d6','\u05d6\u05e2\u05e0\u05e2\u05df','\u05d6\u05d0\u05dc',
  '\u05d5\u05d5\u05d9\u05e1\u05df','\u05d5\u05d5\u05d9\u05e1\u05e0\u05d9\u05e7','\u05e8\u05d5\u05e4\u05df','\u05e8\u05d5\u05e4\u05e2\u05df','\u05d1\u05d0\u05e7\u05d5\u05de\u05e2\u05df','\u05d1\u05e2\u05d8\u05df','\u05d2\u05e2\u05e4\u05d9\u05e0\u05e2\u05df','\u05d6\u05d5\u05db\u05df','\u05e7\u05d5\u05de\u05e2\u05df','\u05d2\u05d9\u05d9\u05df',
  // adverbs, particles, articles
  '\u05d0\u05d6\u05d5\u05d9','\u05e0\u05d9\u05e9\u05d8','\u05e7\u05d9\u05d9\u05df','\u05d3\u05e2\u05e8','\u05d3\u05d0\u05e1','\u05d3\u05d9','\u05e4\u05d5\u05e0\u05e2\u05dd','\u05d0\u05d5\u05d9\u05da','\u05d0\u05d5\u05d9\u05d1','\u05d0\u05d1\u05e2\u05e8','\u05d0\u05d3\u05e2\u05e8',
  '\u05d4\u05d9\u05d9\u05e0\u05d8','\u05de\u05d0\u05e8\u05d2\u05df','\u05de\u05d0\u05e8\u05d2\u05e2\u05df','\u05d9\u05e2\u05e6\u05d8','\u05d3\u05d0\u05e8\u05d8','\u05e2\u05e4\u05e2\u05e1','\u05e9\u05d5\u05d9\u05df','\u05d2\u05d5\u05d8','\u05d1\u05d9\u05d8\u05e2','\u05d3\u05d0\u05e0\u05e7','\u05d3\u05d0\u05e0\u05e7\u05e2\u05df',
  // nouns that are Yiddish rather than Hebrew
  '\u05d0\u05d9\u05e0\u05e4\u05d0\u05e8\u05de\u05d0\u05e6\u05d9\u05e2','\u05e7\u05d9\u05e0\u05d3','\u05e7\u05d9\u05e0\u05d3\u05e2\u05e8','\u05de\u05e2\u05e0\u05d8\u05e9','\u05de\u05e2\u05e0\u05d8\u05e9\u05df','\u05d5\u05d5\u05e2\u05d2\u05df','\u05e8\u05d9\u05d9\u05d6\u05df','\u05e0\u05d5\u05d9\u05d8\u05e4\u05d0\u05dc',
  // Added after a Yiddish halachic question ("\u05d8\u05d0\u05e8 \u05d0\u05d9\u05da \u05de\u05d9\u05d8\u05e0\u05e2\u05de\u05e2\u05df \u05d0\u05df \u05d0\u05ea\u05e8\u05d5\u05d2 \u05dc\u05d5\u05d9\u05d8 \u05d4\u05dc\u05db\u05d4?")
  // scored 0-0 and fell to the Hebrew tie-break. None of these is a Hebrew
  // word and none is religious vocabulary - they are ordinary Yiddish verbs
  // and particles, which is the evidence this classifier is meant to run on.
  '\u05d8\u05d0\u05e8','\u05d8\u05d0\u05e8\u05df','\u05de\u05d9\u05d8\u05e0\u05e2\u05de\u05e2\u05df','\u05dc\u05d5\u05d9\u05d8','\u05d8\u05e8\u05d0\u05d2\u05df','\u05d0\u05e4\u05e2\u05df','\u05d0\u05d5\u05e4\u05df','\u05d8\u05d0\u05df','\u05d1\u05e8\u05e2\u05e0\u05d2\u05e2\u05df',
  '\u05e4\u05e8\u05e2\u05d2\u05d8','\u05e4\u05e8\u05e2\u05d2\u05df','\u05d0\u05e0\u05d3\u05e2\u05e8\u05e2','\u05e2\u05de\u05e2\u05e6\u05e2\u05e8','\u05d6\u05d0\u05dc\u05df','\u05de\u05e2\u05d2\u05dc\u05d9\u05da','\u05e9\u05d9\u05e7\u05df'
];
/* Weight 1: real Yiddish, but each also occurs incidentally elsewhere, so on
   its own it is a hint rather than evidence. */
const ASK_YI_WEAK = ['\u05e4\u05d0\u05e8','\u05de\u05d9\u05d8','\u05d3\u05d0','\u05d0\u05dc\u05e2','\u05e0\u05d0\u05da','\u05d0\u05d5\u05d9\u05e3','\u05d0\u05df','\u05e6\u05d5'];
/* Hebrew function words and question words. */
const ASK_HE_WORDS = [
  '\u05de\u05d4','\u05d0\u05d9\u05e4\u05d4','\u05de\u05ea\u05d9','\u05d4\u05d0\u05dd','\u05db\u05de\u05d4','\u05dc\u05de\u05d4','\u05de\u05d3\u05d5\u05e2','\u05d0\u05d9\u05d6\u05d4','\u05d4\u05d9\u05d5\u05dd','\u05de\u05d7\u05e8','\u05e2\u05db\u05e9\u05d9\u05d5',
  '\u05ea\u05d5\u05d3\u05d4','\u05e9\u05dc\u05d5\u05dd','\u05e6\u05e8\u05d9\u05da','\u05e6\u05e8\u05d9\u05db\u05d9\u05dd','\u05e6\u05e8\u05d9\u05db\u05d4','\u05d0\u05e0\u05d9','\u05d0\u05e0\u05d7\u05e0\u05d5','\u05d0\u05ea\u05dd','\u05d4\u05dd','\u05d4\u05d5\u05d0','\u05d4\u05d9\u05d0',
  '\u05d9\u05e9','\u05e9\u05dc','\u05d0\u05ea','\u05d6\u05d4','\u05d6\u05d0\u05ea','\u05e2\u05dd','\u05e2\u05dc','\u05d2\u05dd','\u05e8\u05e7','\u05db\u05dc','\u05dc\u05d0','\u05db\u05df','\u05d8\u05d5\u05d1','\u05d9\u05db\u05d5\u05dc','\u05d9\u05db\u05d5\u05dc\u05d4',
  '\u05dc\u05d3\u05e2\u05ea','\u05dc\u05d7\u05d3\u05e9','\u05dc\u05d4\u05d2\u05d9\u05e9','\u05dc\u05d9\u05e6\u05d5\u05e8','\u05dc\u05e7\u05d1\u05dc','\u05dc\u05de\u05e6\u05d5\u05d0','\u05d1\u05e7\u05e9\u05d4','\u05dc\u05d2\u05d1\u05d9','\u05d0\u05e4\u05e9\u05e8\u05d5\u05ea'
];
/* Genuinely shared - counted for neither side. \u05d0\u05e4\u05e9\u05e8 is ordinary Hebrew
   ("is it possible") and ordinary Yiddish ("maybe"); \u05d0\u05d9\u05da is Hebrew "how" and
   Yiddish "I"; \u05d0\u05d9\u05df is Hebrew "there is no" and Yiddish "in". Scoring any of
   them would decide the sentence on the weakest available evidence. */
const ASK_SHARED_SCRIPT_WORDS = ['\u05d0\u05e4\u05e9\u05e8','\u05d0\u05d9\u05da','\u05d0\u05d9\u05df','\u05d0'];

/* Latin-script Yiddish. Weight 2 = structural Yiddish with no ordinary English
   or French reading. Weight 1 = plausible but collides with other languages. */
const ASK_YI_LATIN_STRONG = ['ikh','vu','ven','ver','vos','darf','vil','visn','wissen',
  'nisht','azoy','haynt','morgn','farvos','vifl','rufn','rufen','bakumen','betn','zukhn',
  'iz','zenen','zayn','zayne','kenen','oykh','epes','shoyn','undz','aykh','gefinen','noytfal',
  // Section 5 of the brief lists both spellings; "morgn" alone assumed a
  // single orthography, which the brief explicitly warns against.
  'aroys','arois','morgen','vemen','velkhe','tor','toren','loyt'];
const ASK_YI_LATIN_WEAK = ['far','mit','dos','der','ken','mir','tsu','ober','nit','veln'];
/* Community vocabulary is shared across all four languages. Section 6 of the
   brief is explicit: these must never decide the language on their own, so
   they carry no weight at all. "Where can I find Shabbos information?" is an
   English sentence and has to stay one. */
const ASK_COMMUNITY_TERMS = ['shabbos','shabbes','shabbat','yom tov','yontif','yomtov',
  'daven','davening','shkia','chatzos','mincha','maariv','hatzolah','eruv','mikvah',
  'kosher','frum','heimish','simcha','tznius','pesach','sukkos','purim','chanukah',
  'rosh hashana','zmanim','etrog','lulav','matzah','shul','minyan'];

function askScriptTokens(s){
  return String(s || '').split(/[^\u0590-\u05ffa-zA-Z0-9\u2019']+/).filter(Boolean);
}

/* Hebrew-block input: decide Hebrew vs Yiddish on accumulated evidence. */
function askScoreHebrewScript(s){
  const toks = askScriptTokens(s).filter(t => /[\u0590-\u05ff]/.test(t));
  let yi = 0, he = 0;
  const seen = new Set();
  toks.forEach(t=>{
    // Strip nikkud/cantillation before the lookup: pointed Yiddish
    // (\u05de\u05d0\u05b8\u05e0\u05d8\u05e8\u05e2\u05d0\u05b7\u05dc) otherwise matches no lexicon entry at all. The
    // pointed-alef orthography check below still runs on the raw string,
    // so the evidence the pointing itself provides is not lost.
    const w = t.replace(/[\u0591-\u05C7]/g,'').replace(/[^\u0590-\u05FF]/g,'');
    if(!w || seen.has(w)) return;
    seen.add(w);
    if(ASK_SHARED_SCRIPT_WORDS.indexOf(w) >= 0) return;
    if(ASK_YI_WORDS.indexOf(w) >= 0) yi += 2;
    else if(ASK_YI_WEAK.indexOf(w) >= 0) yi += 1;
    else if(ASK_HE_WORDS.indexOf(w) >= 0) he += 2;
  });
  // Orthography. Yiddish writes the digraphs \u05d5\u05d5 and \u05d9\u05d9 constantly and Hebrew
  // rarely; the precomposed ligatures and pointed alef occur in no Hebrew text.
  if(/[\u05f0\u05f1\u05f2]/.test(s))       yi += 3;
  if(/[\u05d0][\u05b7\u05b8]/.test(s))     yi += 3;
  if(/\u05d5\u05d5/.test(s))               yi += 3;
  if(/\u05d9\u05d9/.test(s))               yi += 2;
  // Hebrew plural endings are a nudge only: Yiddish borrows plenty of Hebrew
  // nouns (\u05d6\u05de\u05e0\u05d9\u05dd, \u05e1\u05e4\u05e8\u05d9\u05dd) and would otherwise be penalised for it.
  if(/[\u05d0-\u05ea]{3,}(\u05d9\u05dd|\u05d5\u05ea)(\s|$|[?!.,])/.test(s)) he += 1;
  return { yi, he };
}

/* Latin-script input: does this look like transliterated Yiddish? */
function askScoreLatinYiddish(s){
  const toks = String(s || '').toLowerCase().split(/[^a-z']+/).filter(Boolean);
  const low = ' ' + String(s || '').toLowerCase() + ' ';
  let score = 0, strong = 0;
  const seen = new Set();
  toks.forEach(t=>{
    if(seen.has(t)) return;
    seen.add(t);
    if(ASK_COMMUNITY_TERMS.indexOf(t) >= 0) return;   // never decisive
    if(ASK_YI_LATIN_STRONG.indexOf(t) >= 0){ score += 2; strong++; }
    else if(ASK_YI_LATIN_WEAK.indexOf(t) >= 0){ score += 1; }
  });
  ASK_COMMUNITY_TERMS.forEach(t=>{ if(t.indexOf(' ') > 0 && low.indexOf(' '+t+' ') >= 0){ /* no weight */ } });
  return { score, strong };
}

function askDetectLanguage(q){
  const s = String(q || '');

  if(/[\u0590-\u05ff]/.test(s)){
    // Mixed input: a single Hebrew-script word inside an otherwise English
    // sentence does not make the sentence Hebrew or Yiddish. Section 6 asks for
    // the dominant conversational language, so measure it before scoring.
    const toks = askScriptTokens(s);
    const heb  = toks.filter(t => /[\u0590-\u05ff]/.test(t)).length;
    const dominant = toks.length ? (heb / toks.length) : 1;
    if(dominant >= 0.34){
      const sc = askScoreHebrewScript(s);
      return sc.yi > sc.he ? 'yi' : 'he';   // tie -> Hebrew, the safer default
    }
    // Otherwise fall through and classify the Latin majority.
  }

  // French markers: accents, elisions, and common question words. Checked as
  // whole words so "est" does not fire on "interest".
  const frWords = /\b(est|es-tu|quand|comment|pourquoi|quel|quelle|quels|quelles|o\u00f9|puis|peux|peut|dois|faut|besoin|trouver|obtenir|demander|prier|nourriture|heure|aujourd|demain|cette|mon|ma|mes|notre|votre|nous|vous|je|j'ai|c'est|qu'est|s'il|de la|du|des|le|la|les|une|un|pour|avec|dans|sur)\b/gi;
  const frAccents = /[\u00e0\u00e2\u00e4\u00e7\u00e8\u00e9\u00ea\u00eb\u00ee\u00ef\u00f4\u00f6\u00f9\u00fb\u00fc]/;
  // Some words are decisive on their own: no English question begins with
  // "Comment", "Quand", "Pourquoi" or "Est-ce que". Without this, short French
  // questions with no accent - "Comment contacter Hatzolah?" - were read as
  // English and answered in English. Checked before Yiddish so that French
  // "vos" ("vos documents") cannot be read as Yiddish "vos" ("what").
  const frStrong = /\b(comment|quand|pourquoi|o\u00f9|quelle?s?|est-ce que|puis-je|peut-on|combien|qu'est-ce)\b/i;
  if(frStrong.test(s)) return 'fr';

  // Transliterated Yiddish. Requires one structural word AND corroboration:
  // a single "far" or "ken" in an English sentence is not evidence.
  const yl = askScoreLatinYiddish(s);
  if(yl.strong >= 1 && yl.score >= 3) return 'yi';

  const hits = (s.match(frWords) || []).length;
  // Otherwise: two French function words, or one plus an accent. A single "le"
  // or "de" inside an English sentence is not enough.
  if(hits >= 2 || (hits >= 1 && frAccents.test(s))) return 'fr';
  return 'en';
}

/* Pick the right string from a {en, fr, he, yi} object.

   A missing translation still degrades to English rather than to blank, but it
   is recorded rather than swallowed: __askMissingYi is what the admin test
   panel and the test suite read to prove no user-facing string is silently
   answering a Yiddish question in English. */
const __askMissingYi = new Set();
function askT(obj, lang){
  if(typeof obj === 'string') return obj;
  if(!obj) return '';
  if(obj[lang]) return obj[lang];
  if(lang === 'yi' && !obj.yi) __askMissingYi.add(String(obj.en || '').slice(0, 120));
  return obj.en || '';
}

function askAnswerShape(){
  return { answer:'', sources:[], actions:[], timeSensitive:false, handled:false, handler:'', lang:'en', location:'', halachic:false };
}

/* ---------- halachic-question guard ----------
   CJHQ is not a religious authority. Before this existed, "Can I carry in the
   eruv on Shabbos according to halacha?" reached askEruv and came back with
   the eruv STATUS answer - silently answering a halachic question with a
   practical one. That is the failure this guard prevents.

   It does not refuse. It runs the practical handlers, presents whatever CJHQ
   actually knows under a clear label, and adds a referral for the ruling
   itself. No rabbi, organisation, phone number or directory is named: CJHQ has
   no verified rabbinic directory, and inventing one is the same failure mode
   as an invented emergency number.

   Deliberately narrow. Mentioning Shabbos, eruv, mikvah, kosher, tefillin,
   mezuzah, an etrog or a yom tov is NOT halachic framing - those are the
   ordinary subjects of practical questions. The trigger requires the user to
   be asking for the ruling: an explicit halachic adjective, "according to
   halacha" and its equivalents, or mutar / assur / \u05d8\u05d0\u05e8 \u05de\u05e2\u05df.                  */
const ASK_HALACHIC_RE = new RegExp([
  // English - adjective forms, explicit "according to" framing, and loanwords
  // that are only ever used to ask for a ruling.
  'halach(?:ic|ically|ik)\\b', 'halakh(?:ic|ically)\\b',
  'according to (?:the )?halach', 'according to (?:the )?halakh',
  'according to jewish law', 'under jewish law', 'per halach',
  '\\bmutar\\b', '\\bassur\\b', '\\bpsak\\b', '\\bposek\\b', '\\bshaila\\b', '\\bsheilah\\b',
  // French
  'selon la halach', 'selon la halakh', 'halakhique', 'halachique',
  'selon la loi juive', 'apr\u00e8s la halach', 'apres la halach',
  // Hebrew - the framing only. Never the bare word \u05d4\u05dc\u05db\u05d4 and never bare
  // \u05de\u05d5\u05ea\u05e8, because "\u05d4\u05d0\u05dd \u05de\u05d5\u05ea\u05e8 \u05dc\u05d7\u05e0\u05d5\u05ea \u05db\u05d0\u05df?" is a parking question.
  '\u05e2\u05dc \u05e4\u05d9 \u05d4\u05d4\u05dc\u05db\u05d4', '\u05e2\u05dc \u05e4\u05d9 \u05d4\u05dc\u05db\u05d4', '\u05dc\u05e4\u05d9 \u05d4\u05d4\u05dc\u05db\u05d4', '\u05dc\u05e4\u05d9 \u05d4\u05dc\u05db\u05d4',
  '\u05de\u05d4 \u05d4\u05d4\u05dc\u05db\u05d4', '\u05e4\u05e1\u05e7 \u05d4\u05dc\u05db\u05d4', '\u05d4\u05dc\u05db\u05ea\u05d9\u05ea', '\u05e9\u05d0\u05dc\u05d4 \u05d4\u05dc\u05db\u05ea\u05d9\u05ea',
  // Yiddish
  '\u05dc\u05d5\u05d9\u05d8 \u05d4\u05dc\u05db\u05d4', '\u05dc\u05d5\u05d9\u05d8 \u05d3\u05e2\u05e8 \u05d4\u05dc\u05db\u05d4', '\u05dc\u05d5\u05d9\u05d8 \u05d3\u05d9 \u05d4\u05dc\u05db\u05d4',
  '\u05d8\u05d0\u05e8 \u05de\u05e2\u05df', '\u05d8\u05d0\u05e8 \u05d0\u05d9\u05da', '\u05d8\u05d0\u05e8 \u05d0\u05d9\u05e8', '\u05d0\u05d9\u05d6 \u05d3\u05d0\u05e1 \u05de\u05d5\u05ea\u05e8', '\u05d4\u05dc\u05db\u05ea\u05d9\u05e9\u05e2'
].join('|'), 'i');

/* The practical chain, named once so the guard and the entry point cannot
   drift apart. askHalachic is NOT in it - it runs ahead of it. */
function askPracticalHandlers(){
  return [askEruv, askEmergency, askZmanim, askCalendar,
          askCommunityDirectory, askCjhqResources];
}

function askHalachic(q){
  if(!ASK_HALACHIC_RE.test(String(q || ''))) return null;
  const L = askDetectLanguage(q);

  // Still give the person what CJHQ genuinely knows. The practical handlers
  // run exactly as they normally would; only the presentation changes.
  let practical = null;
  for(const h of askPracticalHandlers()){
    const out = h(q);
    if(out){ practical = out; break; }
  }

  const r = practical || askAnswerShape();
  r.lang = L;
  r.halachic = true;
  r.handled = true;
  r.handler = practical ? ('Halachic + ' + (practical.handler || 'none')) : 'Halachic';

  const referral = askT({
    en:'CJHQ can provide practical, travel and government information, but does not provide halachic rulings. For the halachic ruling on this question, please consult your rov.',
    fr:'Le CJHQ peut fournir des renseignements pratiques, de voyage et gouvernementaux, mais ne donne pas de d\u00e9cisions halakhiques. Pour la d\u00e9cision halakhique concernant cette question, veuillez consulter votre rav.',
    he:'CJHQ \u05d9\u05db\u05d5\u05dc \u05dc\u05e1\u05e4\u05e7 \u05de\u05d9\u05d3\u05e2 \u05de\u05e2\u05e9\u05d9, \u05de\u05d9\u05d3\u05e2 \u05d1\u05e0\u05d5\u05e9\u05d0\u05d9 \u05e0\u05e1\u05d9\u05e2\u05d5\u05ea \u05d5\u05de\u05d9\u05d3\u05e2 \u05de\u05de\u05e9\u05dc\u05ea\u05d9, \u05d0\u05da \u05d0\u05d9\u05e0\u05d5 \u05e0\u05d5\u05ea\u05df \u05e4\u05e1\u05e7\u05d9 \u05d4\u05dc\u05db\u05d4. \u05dc\u05e7\u05d1\u05dc\u05ea \u05d4\u05db\u05e8\u05e2\u05d4 \u05d4\u05dc\u05db\u05ea\u05d9\u05ea \u05d1\u05e9\u05d0\u05dc\u05d4 \u05d6\u05d5, \u05d9\u05e9 \u05dc\u05d4\u05ea\u05d9\u05d9\u05e2\u05e5 \u05e2\u05dd \u05d4\u05e8\u05d1 \u05e9\u05dc\u05db\u05dd.',
    yi:'CJHQ \u05e7\u05e2\u05df \u05e6\u05d5\u05e9\u05d8\u05e2\u05dc\u05df \u05e4\u05e8\u05d0\u05e7\u05d8\u05d9\u05e9\u05e2, \u05e8\u05d9\u05d9\u05d6\u05e2 \u05d0\u05d5\u05df \u05e8\u05e2\u05d2\u05d9\u05e8\u05d5\u05e0\u05d2\u05e1\u05be\u05d0\u05d9\u05e0\u05e4\u05d0\u05e8\u05de\u05d0\u05e6\u05d9\u05e2, \u05d0\u05d1\u05e2\u05e8 \u05d2\u05d9\u05d8 \u05e0\u05d9\u05e9\u05d8 \u05e7\u05d9\u05d9\u05df \u05d4\u05dc\u05db\u05ea\u05d9\u05e9\u05e2 \u05e4\u05e1\u05e7\u05d9 \u05d3\u05d9\u05df. \u05e4\u05d0\u05e8 \u05d3\u05e2\u05e8 \u05d4\u05dc\u05db\u05ea\u05d9\u05e9\u05e2\u05e8 \u05d4\u05db\u05e8\u05e2\u05d4 \u05d0\u05d9\u05df \u05d3\u05e2\u05e8 \u05e9\u05d0\u05dc\u05d4, \u05d1\u05d9\u05d8\u05e2 \u05e4\u05e8\u05e2\u05d2\u05d8 \u05d0\u05d9\u05d9\u05e2\u05e8 \u05e8\u05d1.'
  }, L);

  const label = askT({
    en:'Practical information from CJHQ:',
    fr:'Renseignements pratiques du CJHQ :',
    he:'\u05de\u05d9\u05d3\u05e2 \u05de\u05e2\u05e9\u05d9 \u05de-CJHQ:',
    yi:'\u05e4\u05e8\u05d0\u05e7\u05d8\u05d9\u05e9\u05e2 \u05d0\u05d9\u05e0\u05e4\u05d0\u05e8\u05de\u05d0\u05e6\u05d9\u05e2 \u05e4\u05d5\u05df CJHQ:'
  }, L);

  r.answer = (practical && practical.answer)
    ? (label + '\n' + practical.answer + '\n\n' + referral)
    : referral;
  return r;
}

function askEruv(q){
  // English, French (erouv/érouv) and Hebrew script.
  if(!/eruv|eiruv|erouv|\u05e2\u05d9\u05e8\u05d5\u05d1|\u05e2\u05d9\u05e8\u05d5\u05d5/i.test(q)) return null;
  const r = askAnswerShape();
  const L = askDetectLanguage(q); r.lang = L;
  r.handled = true; r.handler = 'Eruv'; r.timeSensitive = true;
  r.answer = askT({
    en:'Eruv status changes week to week, so I will not state whether it is up. Check the official Montreal Eruv page, which is updated by the people who inspect it.',
    fr:'Le statut de l\u2019\u00e9rouv change d\u2019une semaine \u00e0 l\u2019autre. Je n\u2019affirmerai donc pas s\u2019il est en fonction. Consultez la page officielle de l\u2019\u00c9rouv de Montr\u00e9al, mise \u00e0 jour par ceux qui l\u2019inspectent.',
    he:'\u05de\u05e6\u05d1 \u05d4\u05e2\u05d9\u05e8\u05d5\u05d1 \u05de\u05e9\u05ea\u05e0\u05d4 \u05de\u05e9\u05d1\u05d5\u05e2 \u05dc\u05e9\u05d1\u05d5\u05e2, \u05dc\u05db\u05df \u05dc\u05d0 \u05d0\u05e6\u05d9\u05d9\u05df \u05d0\u05dd \u05d4\u05d5\u05d0 \u05ea\u05e7\u05d9\u05df. \u05d9\u05e9 \u05dc\u05d1\u05d3\u05d5\u05e7 \u05d1\u05d0\u05ea\u05e8 \u05d4\u05e8\u05e9\u05de\u05d9 \u05e9\u05dc \u05e2\u05d9\u05e8\u05d5\u05d1 \u05de\u05d5\u05e0\u05d8\u05e8\u05d9\u05d0\u05dc.',
    yi:'\u05d3\u05e2\u05e8 \u05de\u05e6\u05d1 \u05e4\u05d5\u05e0\u05e2\u05dd \u05e2\u05d9\u05e8\u05d5\u05d1 \u05e2\u05e0\u05d3\u05e2\u05e8\u05d8 \u05d6\u05d9\u05da \u05d9\u05e2\u05d3\u05e2 \u05d5\u05d5\u05d0\u05da, \u05d3\u05e2\u05e8\u05d9\u05d1\u05e2\u05e8 \u05d6\u05d0\u05d2 \u05d0\u05d9\u05da \u05e0\u05d9\u05e9\u05d8 \u05e6\u05d9 \u05e2\u05e8 \u05d0\u05d9\u05d6 \u05d2\u05d5\u05d8 \u05d0\u05d3\u05e2\u05e8 \u05e0\u05d9\u05e9\u05d8. \u05e7\u05d5\u05e7\u05d8 \u05e0\u05d0\u05da \u05d0\u05d5\u05d9\u05e3 \u05d3\u05e2\u05e8 \u05d0\u05e4\u05d9\u05e6\u05d9\u05e2\u05dc\u05e2\u05e8 \u05de\u05d0\u05e0\u05d8\u05e8\u05e2\u05d0\u05dc \u05e2\u05d9\u05e8\u05d5\u05d1 \u05d1\u05dc\u05d0\u05d8 \u2014 \u05d6\u05d9\u05d9 \u05e4\u05e8\u05d9\u05e9\u05df \u05e2\u05e1 \u05d0\u05d5\u05d9\u05e3.'
  }, L);
  // Actions come from the structured record, so changing the official URL is a
  // one-line edit rather than a hunt through the handlers.
  const E = ASK_ERUV_RECORD;
  r.actions = [
    { label: askT({en:'Check Eruv Status', fr:'V\u00e9rifier le statut de l\u2019\u00e9rouv', he:'\u05d1\u05d3\u05d9\u05e7\u05ea \u05de\u05e6\u05d1 \u05d4\u05e2\u05d9\u05e8\u05d5\u05d1', yi:'\u05d6\u05e2\u05d8 \u05d3\u05e2\u05dd \u05e2\u05d9\u05e8\u05d5\u05d1 \u05de\u05e6\u05d1'}, L), url:E.statusPage, kind:'link' },
    { label: askT({en:'View Eruv Map', fr:'Voir la carte de l\u2019\u00e9rouv', he:'\u05de\u05e4\u05ea \u05d4\u05e2\u05d9\u05e8\u05d5\u05d1', yi:'\u05d6\u05e2\u05d8 \u05d3\u05d9 \u05e2\u05d9\u05e8\u05d5\u05d1 \u05de\u05d0\u05e4\u05e2'}, L), url:E.mapUrl, kind:'map' },
    { label: askT({en:'Eruv Website', fr:'Site de l\u2019\u00e9rouv', he:'\u05d0\u05ea\u05e8 \u05d4\u05e2\u05d9\u05e8\u05d5\u05d1', yi:'\u05e2\u05d9\u05e8\u05d5\u05d1 \u05d5\u05d5\u05e2\u05d1\u05d6\u05d9\u05d9\u05d8\u05dc'}, L), url:E.website, kind:'link' }
  ];
  r.sources = askSortSources([{ name:E.organization, url:E.website, type:'Eruv',
                                authoritative:true, timeSensitive:true, lastVerified:E.lastVerified }]);
  return r;
}

function askEmergency(q){
  if(!/hatzol|hatzalah|ambulance|emergency|paramedic|urgence|ambulancier|noytfal|\u05d4\u05e6\u05dc\u05d4|\u05e0\u05d5\u05d9\u05d8\u05e4\u05d0\u05dc|\u05d0\u05de\u05d1\u05d5\u05dc\u05d0\u05e0\u05e1/i.test(q)) return null;
  const r = askAnswerShape();
  const L = askDetectLanguage(q); r.lang = L;
  r.handled = true; r.handler = 'Emergency';
  r.answer = askT({
    en:'If this is a life-threatening emergency, call 911 first.\n\nHatzolah Montreal is the community volunteer emergency medical service. I will not quote a phone number from memory. Use the official site so you get the current one.',
    fr:'S\u2019il s\u2019agit d\u2019une urgence vitale, composez d\u2019abord le 911.\n\nHatzolah Montr\u00e9al est le service m\u00e9dical d\u2019urgence b\u00e9n\u00e9vole de la communaut\u00e9. Je ne citerai pas un num\u00e9ro de m\u00e9moire. Consultez le site officiel pour le num\u00e9ro \u00e0 jour.',
    he:'\u05d1\u05de\u05e7\u05e8\u05d4 \u05e9\u05dc \u05e1\u05db\u05e0\u05ea \u05d7\u05d9\u05d9\u05dd \u05d9\u05e9 \u05dc\u05d4\u05ea\u05e7\u05e9\u05e8 \u05ea\u05d7\u05d9\u05dc\u05d4 \u05dc-911.\n\n\u05d4\u05e6\u05dc\u05d4 \u05de\u05d5\u05e0\u05d8\u05e8\u05d9\u05d0\u05dc \u05d4\u05d5\u05d0 \u05e9\u05d9\u05e8\u05d5\u05ea \u05d4\u05d7\u05d9\u05e8\u05d5\u05dd \u05d4\u05e7\u05d4\u05d9\u05dc\u05ea\u05d9. \u05dc\u05d0 \u05d0\u05e6\u05d8\u05d8 \u05de\u05e1\u05e4\u05e8 \u05d8\u05dc\u05e4\u05d5\u05df \u05de\u05d4\u05d6\u05d9\u05db\u05e8\u05d5\u05df. \u05d9\u05e9 \u05dc\u05d4\u05e9\u05ea\u05de\u05e9 \u05d1\u05d0\u05ea\u05e8 \u05d4\u05e8\u05e9\u05de\u05d9.',
    yi:'\u05d0\u05d5\u05d9\u05d1 \u05e2\u05e1 \u05d0\u05d9\u05d6 \u05d0 \u05dc\u05e2\u05d1\u05e0\u05e1\u05be\u05d2\u05e2\u05e4\u05d0\u05e8, \u05e8\u05d5\u05e4\u05d8 \u05e2\u05e8\u05e9\u05d8 911.\n\n\u05d4\u05e6\u05dc\u05d4 \u05de\u05d0\u05e0\u05d8\u05e8\u05e2\u05d0\u05dc \u05d0\u05d9\u05d6 \u05d3\u05e2\u05e8 \u05e7\u05d4\u05d9\u05dc\u05d4\u05be\u05e1\u05e2\u05e8\u05d5\u05d5\u05d9\u05e1 \u05e4\u05d0\u05e8 \u05de\u05e2\u05d3\u05d9\u05e6\u05d9\u05e0\u05d9\u05e9\u05e2 \u05e0\u05d5\u05d9\u05d8\u05e4\u05d0\u05dc\u05df. \u05d0\u05d9\u05da \u05d5\u05d5\u05e2\u05dc \u05e0\u05d9\u05e9\u05d8 \u05d6\u05d0\u05d2\u05df \u05e7\u05d9\u05d9\u05df \u05d8\u05e2\u05dc\u05e2\u05e4\u05d0\u05df \u05e0\u05d5\u05de\u05e2\u05e8 \u05e4\u05d5\u05df \u05d6\u05db\u05e8\u05d5\u05df. \u05e0\u05d5\u05e6\u05d8 \u05d3\u05d9 \u05d0\u05e4\u05d9\u05e6\u05d9\u05e2\u05dc\u05e2 \u05d5\u05d5\u05e2\u05d1\u05d6\u05d9\u05d9\u05d8\u05dc \u05e6\u05d5 \u05d1\u05d0\u05e7\u05d5\u05de\u05e2\u05df \u05d3\u05e2\u05dd \u05e8\u05d9\u05db\u05d8\u05d9\u05d2\u05df \u05e0\u05d5\u05de\u05e2\u05e8.'
  }, L);
  // A "Call" button appears only if an admin has entered a verified number.
  // emergencyNumbers is empty by design, so today there is no call action -
  // which is correct: a wrong emergency number is worse than none.
  const H = ASK_HATZOLAH_RECORD;
  r.actions = [];
  (H.emergencyNumbers || []).forEach(n=>{
    r.actions.push({ label: askT({en:'Call ' + H.organization, fr:'Appeler ' + H.organization,
                                  he:'\u05d4\u05ea\u05e7\u05e9\u05e8\u05d5 \u05dc' + H.organization,
                                  yi:'\u05e8\u05d5\u05e4\u05d8 ' + H.organization}, L),
                     url:'tel:' + String(n).replace(/[^0-9+]/g,''), kind:'phone' });
  });
  r.actions.push({ label: askT({en:H.organization + ' Website', fr:'Site de ' + H.organization,
                                he:'\u05d0\u05ea\u05e8 ' + H.organization,
                                yi:H.organization + ' \u05d5\u05d5\u05e2\u05d1\u05d6\u05d9\u05d9\u05d8\u05dc'}, L), url:H.website, kind:'link' });
  if(H.mapUrl) r.actions.push({ label: askT({en:'View Map', fr:'Voir la carte', he:'\u05de\u05e4\u05d4', yi:'\u05d6\u05e2\u05d8 \u05d3\u05d9 \u05de\u05d0\u05e4\u05e2'}, L), url:H.mapUrl, kind:'map' });
  r.sources = askSortSources([{ name:H.organization, url:H.website, type:'Emergency',
                                authoritative:true, timeSensitive:false,
                                serviceArea:H.serviceArea, lastVerified:H.lastVerified }]);
  return r;
}

function askZmanim(q){
  if(!/zman|shkia|shkiah|sunset|sunrise|candle.?light|hadlak|tzeis|tzais|havdal|neitz|alos|alot|coucher du soleil|bougies|allumage/i.test(q)
     && !/(shabbo?s|shabbat|chabbat|\u05e9\u05d1\u05ea).{0,20}(end|finish|out|over|termine|fini)/i.test(q)
     && !/\u05e9\u05e7\u05d9\u05e2\u05d4|\u05d6\u05de\u05df|\u05d6\u05de\u05e0\u05d9\u05dd|\u05d4\u05d3\u05dc\u05e7\u05ea \u05e0\u05e8\u05d5\u05ea|\u05e0\u05e8\u05d5\u05ea|\u05dc\u05d9\u05db\u05d8|\u05d1\u05e0\u05d7\u05df/i.test(q)) return null;
  const r = askAnswerShape();
  const L = askDetectLanguage(q); r.lang = L;
  const loc = askDetectLocation(q);
  r.location = loc.name;
  r.handled = true; r.handler = 'Zmanim'; r.timeSensitive = true;
  const url = 'https://www.hebcal.com/zmanim?geonameid=' + loc.geonameid;
  r.answer = askT({
    en:'Zmanim change daily, so these are never answered from memory. The live lookup is not connected yet. Today\u2019s times for ' + loc.name + ' are on Hebcal.',
    fr:'Les zmanim changent chaque jour; ils ne sont donc jamais donn\u00e9s de m\u00e9moire. La consultation en direct n\u2019est pas encore branch\u00e9e. Les heures du jour pour ' + loc.name + ' se trouvent sur Hebcal.',
    he:'\u05d4\u05d6\u05de\u05e0\u05d9\u05dd \u05de\u05e9\u05ea\u05e0\u05d9\u05dd \u05de\u05d3\u05d9 \u05d9\u05d5\u05dd, \u05dc\u05db\u05df \u05d4\u05dd \u05dc\u05e2\u05d5\u05dc\u05dd \u05dc\u05d0 \u05e0\u05de\u05e1\u05e8\u05d9\u05dd \u05de\u05d4\u05d6\u05d9\u05db\u05e8\u05d5\u05df. \u05d4\u05d6\u05de\u05e0\u05d9\u05dd \u05e2\u05d1\u05d5\u05e8 ' + loc.name + ' \u05e0\u05de\u05e6\u05d0\u05d9\u05dd \u05d1-Hebcal.',
    yi:'\u05d6\u05de\u05e0\u05d9\u05dd \u05e2\u05e0\u05d3\u05e2\u05e8\u05df \u05d6\u05d9\u05da \u05d9\u05e2\u05d3\u05df \u05d8\u05d0\u05d2, \u05d3\u05e2\u05e8\u05d9\u05d1\u05e2\u05e8 \u05d6\u05d0\u05d2 \u05d0\u05d9\u05da \u05d6\u05d9\u05d9 \u05e7\u05d9\u05d9\u05e0\u05de\u05d0\u05dc \u05e0\u05d9\u05e9\u05d8 \u05e4\u05d5\u05df \u05d6\u05db\u05e8\u05d5\u05df. \u05d3\u05d9 \u05dc\u05e2\u05d1\u05e2\u05d3\u05d9\u05d2\u05e2 \u05e0\u05d0\u05db\u05e4\u05e8\u05e2\u05d2 \u05d0\u05d9\u05d6 \u05e0\u05d0\u05da \u05e0\u05d9\u05e9\u05d8 \u05d0\u05e0\u05d2\u05e2\u05e9\u05dc\u05d0\u05e1\u05df. \u05d4\u05d9\u05d9\u05e0\u05d8\u05d9\u05d2\u05e2 \u05d6\u05de\u05e0\u05d9\u05dd \u05e4\u05d0\u05e8 ' + loc.name + ' \u05d2\u05e2\u05e4\u05d9\u05e0\u05d8 \u05de\u05e2\u05df \u05d0\u05d5\u05d9\u05e3 Hebcal.'
  }, L);
  r.actions = [{ label: askT({en:'Today\u2019s ' + loc.name + ' Zmanim',
                              fr:'Zmanim du jour \u2014 ' + loc.name,
                              he:'\u05d6\u05de\u05e0\u05d9 \u05d4\u05d9\u05d5\u05dd \u2014 ' + loc.name,
                              yi:'\u05d4\u05d9\u05d9\u05e0\u05d8\u05d9\u05d2\u05e2 \u05d6\u05de\u05e0\u05d9\u05dd \u2014 ' + loc.name}, L),
                 url:url, kind:'link' }];
  r.sources = askSortSources([{ name:'Hebcal \u2014 ' + loc.name + ' Zmanim', url:url,
                                type:'Zmanim', authoritative:true, timeSensitive:true }]);
  return r;
}

function askCalendar(q){
  if(!/rosh hashan|roch hachana|yom kippur|kippour|sukkot|succos|souccot|pesach|passover|p\u00e2que|shavuot|shavuos|chavouot|purim|pourim|chanuk|hanukk|hanouca|tisha|hebrew date|jewish calendar|calendrier juif|yom tov|f\u00eate juive|fast day|je\u00fbne/i.test(q)
     && !/\u05e8\u05d0\u05e9 \u05d4\u05e9\u05e0\u05d4|\u05d9\u05d5\u05dd \u05db\u05d9\u05e4\u05d5\u05e8|\u05e1\u05d5\u05db\u05d5\u05ea|\u05e1\u05d5\u05db\u05d5\u05e1|\u05e4\u05e1\u05d7|\u05e9\u05d1\u05d5\u05e2\u05d5\u05ea|\u05e4\u05d5\u05e8\u05d9\u05dd|\u05d7\u05e0\u05d5\u05db\u05d4|\u05dc\u05d5\u05d7 \u05e9\u05e0\u05d4|\u05d9\u05d5\u05dd \u05d8\u05d5\u05d1|\u05d9\u05d5\u05dd\u05d8\u05d5\u05d1/i.test(q)) return null;
  const r = askAnswerShape();
  const L = askDetectLanguage(q); r.lang = L;
  r.handled = true; r.handler = 'Calendar';
  r.answer = askT({
    en:'Holiday dates move every year, so I will not state one until the calendar lookup is connected. Hebcal has the current dates and can add them to your calendar.',
    fr:'Les dates des f\u00eates changent chaque ann\u00e9e; je n\u2019en indiquerai donc aucune tant que la consultation du calendrier n\u2019est pas branch\u00e9e. Hebcal a les dates \u00e0 jour et peut les ajouter \u00e0 votre calendrier.',
    he:'\u05ea\u05d0\u05e8\u05d9\u05db\u05d9 \u05d4\u05d7\u05d2\u05d9\u05dd \u05de\u05e9\u05ea\u05e0\u05d9\u05dd \u05de\u05d3\u05d9 \u05e9\u05e0\u05d4, \u05dc\u05db\u05df \u05dc\u05d0 \u05d0\u05e6\u05d9\u05d9\u05df \u05ea\u05d0\u05e8\u05d9\u05da \u05e2\u05d3 \u05e9\u05d9\u05d7\u05d5\u05d1\u05e8 \u05dc\u05d5\u05d7 \u05d4\u05e9\u05e0\u05d4. \u05d1-Hebcal \u05d9\u05e9 \u05d0\u05ea \u05d4\u05ea\u05d0\u05e8\u05d9\u05db\u05d9\u05dd \u05d4\u05e2\u05d3\u05db\u05e0\u05d9\u05d9\u05dd.',
    yi:'\u05d9\u05d5\u05dd \u05d8\u05d5\u05d1 \u05d3\u05d0\u05d8\u05d5\u05de\u05e1 \u05e2\u05e0\u05d3\u05e2\u05e8\u05df \u05d6\u05d9\u05da \u05d9\u05e2\u05d3\u05e2\u05e1 \u05d9\u05d0\u05e8, \u05d3\u05e2\u05e8\u05d9\u05d1\u05e2\u05e8 \u05d5\u05d5\u05e2\u05dc \u05d0\u05d9\u05da \u05e0\u05d9\u05e9\u05d8 \u05d6\u05d0\u05d2\u05df \u05e7\u05d9\u05d9\u05df \u05d3\u05d0\u05d8\u05d5\u05dd \u05d1\u05d9\u05d6 \u05d3\u05e2\u05e8 \u05dc\u05d5\u05d7 \u05d0\u05d9\u05d6 \u05d0\u05e0\u05d2\u05e2\u05e9\u05dc\u05d0\u05e1\u05df. Hebcal \u05d4\u05d0\u05d8 \u05d3\u05d9 \u05d9\u05e2\u05e6\u05d8\u05d9\u05d2\u05e2 \u05d3\u05d0\u05d8\u05d5\u05de\u05e1.'
  }, L);
  r.actions = [{ label: askT({en:'Jewish Calendar (Hebcal)', fr:'Calendrier juif (Hebcal)', he:'\u05dc\u05d5\u05d7 \u05e9\u05e0\u05d4 \u05e2\u05d1\u05e8\u05d9 (Hebcal)', yi:'\u05d0\u05d9\u05d3\u05d9\u05e9\u05e2\u05e8 \u05dc\u05d5\u05d7 (Hebcal)'}, L),
                 url:'https://www.hebcal.com/', kind:'link' }];
  r.sources = [{ name:'Hebcal \u2014 Jewish Calendar', url:'https://www.hebcal.com/', type:'Calendar', authoritative:true, timeSensitive:false }];
  return r;
}

/* CJHQ does not hold a directory of shuls, mikvaot, kosher food or minyanim -
   that is FindMTL territory, and FindMTL is not integrated. Without this guard
   such questions leaked into the resource matcher on an incidental word:
   "What time does the mikvah on Van Horne close?" matched a CJHQ resource
   because CJHQ's own address is on Van Horne. Answering a mikvah question with
   a passport page is worse than saying we do not have it. */
function askCommunityDirectory(q){
  const isDirectory = /mikvah|mikveh|mikv\u00e9|\u05de\u05e7\u05d5\u05d5\u05d4|\u05de\u05d9\u05e7\u05d5\u05d5\u05d4|minyan|minyen|\u05de\u05e0\u05d9\u05d9\u05df|shul|schul|synagogue|\u05e9\u05d5\u05dc|\u05d1\u05d9\u05ea \u05db\u05e0\u05e1\u05ea|daven|davening|davenen|pray|prier|\u05d3\u05d0\u05d5\u05d5\u05e0\u05e2\u05df|\u05dc\u05d4\u05ea\u05e4\u05dc\u05dc|kosher|casher|kashrut|cacher|\u05db\u05e9\u05e8/i.test(q);
  if(!isDirectory) return null;
  const r = askAnswerShape();
  const L = askDetectLanguage(q); r.lang = L;
  r.handler = 'Community Directory';

  // Answer from the registry when CJHQ has verified entries. The registry ships
  // EMPTY on purpose: no shul, mikvah or kosher listing is invented here, and
  // an unverified entry is worse than no entry for this kind of question.
  const type = /mikvah|mikveh|mikv\u00e9|\u05de\u05e7\u05d5\u05d5\u05d4/i.test(q) ? 'mikvah'
             : /kosher|casher|kashrut|cacher|\u05db\u05e9\u05e8/i.test(q) ? 'kosher'
             : /minyan|minyen|\u05de\u05e0\u05d9\u05d9\u05df/i.test(q) ? 'minyan'
             : 'shul';
  const hits = (askDirectoryEntries || []).filter(e => e && e.active !== false && e.type === type);

  if(hits.length){
    r.handled = true;
    r.answer = askT({
      en:'CJHQ has ' + hits.length + ' verified listing' + (hits.length===1?'':'s') + ' for this. Details and hours can change, so confirm before relying on them.',
      fr:'CJHQ a ' + hits.length + ' inscription' + (hits.length===1?'':'s') + ' v\u00e9rifi\u00e9e' + (hits.length===1?'':'s') + '. Les d\u00e9tails et les heures peuvent changer; confirmez avant de vous y fier.',
      he:'\u05dc-CJHQ \u05d9\u05e9 ' + hits.length + ' \u05e8\u05e9\u05d5\u05de\u05d5\u05ea \u05de\u05d0\u05d5\u05de\u05ea\u05d5\u05ea. \u05d4\u05e4\u05e8\u05d8\u05d9\u05dd \u05d5\u05d4\u05e9\u05e2\u05d5\u05ea \u05e2\u05e9\u05d5\u05d9\u05d9\u05dd \u05dc\u05d4\u05e9\u05ea\u05e0\u05d5\u05ea; \u05d9\u05e9 \u05dc\u05d0\u05de\u05ea \u05dc\u05e4\u05e0\u05d9 \u05d4\u05e1\u05ea\u05de\u05db\u05d5\u05ea.',
      yi:'CJHQ \u05d4\u05d0\u05d8 ' + hits.length + ' \u05d1\u05d0\u05e9\u05d8\u05e2\u05d8\u05d9\u05d2\u05d8\u05e2 \u05d0\u05d9\u05d9\u05e0\u05d8\u05e8\u05d0\u05d2\u05df \u05d3\u05e2\u05e8\u05d5\u05d9\u05e3. \u05e4\u05e8\u05d8\u05d9\u05dd \u05d0\u05d5\u05df \u05e9\u05e2\u05d4\u05df \u05e7\u05e2\u05e0\u05e2\u05df \u05d6\u05d9\u05da \u05e2\u05e0\u05d3\u05e2\u05e8\u05df, \u05e4\u05d0\u05e8\u05d6\u05d9\u05db\u05e2\u05e8\u05d8 \u05d6\u05d9\u05da \u05e4\u05d0\u05e8 \u05d0\u05d9\u05e8 \u05e4\u05d0\u05e8\u05dc\u05d0\u05d6\u05d8 \u05d6\u05d9\u05da \u05d3\u05e2\u05e8\u05d5\u05d9\u05e3.'
    }, L);
    r.actions = hits.slice(0,4).map(e => ({ label:e.name, url:e.url || '/resources', kind:e.url ? 'link' : 'internal' }));
    r.sources = hits.slice(0,4).map(e => ({
      name:e.name, url:e.url || '', type:'Community',
      authoritative:!!e.verified, timeSensitive:true,
      lastUpdated:e.lastUpdated || ''
    }));
    return r;
  }

  r.handled = false;
  r.answer = askT({
    en:'CJHQ does not yet maintain a verified directory of shuls, mikvaot, minyanim or kosher food, so I cannot answer that reliably. A community directory is the right source for it, and connecting one is still pending.',
    fr:'CJHQ ne tient pas encore un r\u00e9pertoire v\u00e9rifi\u00e9 des synagogues, mikv\u00e9s, minyanim ou commerces cachers; je ne peux donc pas r\u00e9pondre de fa\u00e7on fiable. Un r\u00e9pertoire communautaire serait la bonne source, et son int\u00e9gration est encore \u00e0 venir.',
    he:'\u05dc-CJHQ \u05d0\u05d9\u05df \u05e2\u05d3\u05d9\u05d9\u05df \u05de\u05d0\u05d2\u05e8 \u05de\u05d0\u05d5\u05de\u05ea \u05e9\u05dc \u05d1\u05ea\u05d9 \u05db\u05e0\u05e1\u05ea, \u05de\u05e7\u05d5\u05d5\u05d0\u05d5\u05ea, \u05de\u05e0\u05d9\u05e0\u05d9\u05dd \u05d0\u05d5 \u05de\u05d6\u05d5\u05df \u05db\u05e9\u05e8, \u05dc\u05db\u05df \u05d0\u05d9\u05e0\u05e0\u05d9 \u05d9\u05db\u05d5\u05dc \u05dc\u05e2\u05e0\u05d5\u05ea \u05d1\u05d0\u05d5\u05e4\u05df \u05d0\u05de\u05d9\u05df.',
    yi:'CJHQ \u05d4\u05d0\u05dc\u05d8 \u05e0\u05d0\u05da \u05e0\u05d9\u05e9\u05d8 \u05e7\u05d9\u05d9\u05df \u05d1\u05d0\u05e9\u05d8\u05e2\u05d8\u05d9\u05d2\u05d8\u05e2 \u05e8\u05e9\u05d9\u05de\u05d4 \u05e4\u05d5\u05df \u05e9\u05d5\u05dc\u05df, \u05de\u05e7\u05d5\u05d5\u05d0\u05d5\u05ea, \u05de\u05e0\u05d9\u05e0\u05d9\u05dd \u05d0\u05d3\u05e2\u05e8 \u05db\u05e9\u05e8 \u05e2\u05e1\u05df, \u05d3\u05e2\u05e8\u05d9\u05d1\u05e2\u05e8 \u05e7\u05e2\u05df \u05d0\u05d9\u05da \u05d3\u05d0\u05e1 \u05e0\u05d9\u05e9\u05d8 \u05e2\u05e0\u05d8\u05e4\u05e2\u05e8\u05df \u05d0\u05d5\u05d9\u05e3 \u05d0 \u05e4\u05d0\u05e8\u05dc\u05d0\u05d6\u05dc\u05e2\u05db\u05df \u05d0\u05d5\u05e4\u05df. \u05d0 \u05e7\u05d4\u05d9\u05dc\u05d4 \u05d3\u05d9\u05e8\u05e2\u05e7\u05d8\u05d0\u05e8\u05d9\u05e2 \u05d0\u05d9\u05d6 \u05d3\u05e2\u05e8 \u05e8\u05d9\u05db\u05d8\u05d9\u05d2\u05e2\u05e8 \u05de\u05e7\u05d5\u05e8 \u05d3\u05e2\u05e8\u05e4\u05d0\u05e8, \u05d0\u05d5\u05df \u05d3\u05d0\u05e1 \u05d0\u05e0\u05e6\u05d5\u05e9\u05dc\u05d9\u05e1\u05df \u05e7\u05d5\u05de\u05d8 \u05e0\u05d0\u05da.'
  }, L);
  r.actions = [{ label: askT({en:'CJHQ Resource Centre', fr:'Centre de ressources CJHQ', he:'\u05de\u05e8\u05db\u05d6 \u05d4\u05de\u05e9\u05d0\u05d1\u05d9\u05dd', yi:'CJHQ \u05e8\u05e2\u05e1\u05d5\u05e8\u05e1 \u05e6\u05e2\u05e0\u05d8\u05e2\u05e8'}, L), url:'/resources', kind:'internal' }];
  return r;
}

function askCjhqResources(q){
  const hits = askMatchResources(q, 3);
  if(!hits.length) return null;
  const r = askAnswerShape();
  const L = askDetectLanguage(q); r.lang = L;
  r.handled = true; r.handler = 'CJHQ Resources';
  const top = hits[0].item;
  const topName = (L === 'fr' && top.fr) ? top.fr : top.en;
  r.answer = askT({
    en: hits.length === 1
      ? `CJHQ has a resource for that: ${topName}.`
      : `CJHQ has ${hits.length} resources that look relevant. The closest is ${topName}.`,
    fr: hits.length === 1
      ? `CJHQ a une ressource pour cela : ${topName}.`
      : `CJHQ a ${hits.length} ressources pertinentes. La plus proche est ${topName}.`,
    he: hits.length === 1
      ? `\u05dc-CJHQ \u05d9\u05e9 \u05de\u05e9\u05d0\u05d1 \u05dc\u05db\u05da: ${topName}.`
      : `\u05dc-CJHQ \u05d9\u05e9 ${hits.length} \u05de\u05e9\u05d0\u05d1\u05d9\u05dd \u05e8\u05dc\u05d5\u05d5\u05e0\u05d8\u05d9\u05d9\u05dd. \u05d4\u05e7\u05e8\u05d5\u05d1 \u05d1\u05d9\u05d5\u05ea\u05e8: ${topName}.`,
    yi: hits.length === 1
      ? `CJHQ \u05d4\u05d0\u05d8 \u05d0 \u05e8\u05e2\u05e1\u05d5\u05e8\u05e1 \u05d3\u05e2\u05e8\u05e4\u05d0\u05e8: ${topName}.`
      : `CJHQ \u05d4\u05d0\u05d8 ${hits.length} \u05e8\u05e2\u05e1\u05d5\u05e8\u05e1\u05df \u05d5\u05d5\u05d0\u05e1 \u05d6\u05e2\u05e2\u05df \u05d0\u05d5\u05d9\u05e1 \u05e4\u05d0\u05e1\u05d9\u05d2. \u05d3\u05d9 \u05e0\u05d0\u05e2\u05e0\u05d8\u05e1\u05d8\u05e2 \u05d0\u05d9\u05d6 ${topName}.`
  }, L);
  r.actions = hits.map(h => {
    const nm = (L === 'fr' && h.item.fr) ? h.item.fr : h.item.en;
    return h.item.internalPage
      ? { label:nm, url:'/' + h.item.internalPage, kind:'internal' }
      : { label:nm, url:'/resources/' + h.item.slug, kind:'internal' };
  });
  r.sources = hits.map(h => ({
    name:h.item.en, url:'https://cjhq.org/resources/' + h.item.slug,
    type:'CJHQ', authoritative:true, timeSensitive:false, category:h.category, score:h.score
  }));
  return r;
}

/* ---------- provider-independent entry point ----------
   The UI only ever calls this. Swapping in a real AI gateway means implementing
   ASK_BACKEND.ask() - no other part of the app changes. */
/* Build the context Gemini is allowed to use. Only verified material from the
   deterministic layer goes in - never the raw question, never model memory. */
function askBuildContext(res){
  const parts = [];
  if(res.answer) parts.push('Verified CJHQ answer: ' + res.answer);
  if(res.location) parts.push('Location: ' + res.location);
  if(res.timeSensitive) parts.push('NOTE: this information is time-sensitive. Do not state a specific time, date or status.');
  if(res.halachic) parts.push('NOTE: the user is asking for a halachic ruling. Do NOT give one, do not '
    + 'reason towards one, and do not present the practical information as if it settled the question. '
    + 'Keep the referral to their rov. Do not name any rabbi, organisation or phone number.');
  (res.sources || []).forEach(src=>{
    parts.push('Source: ' + src.name + (src.url ? ' <' + src.url + '>' : '')
      + (src.authoritative ? ' [authoritative]' : '')
      + (src.timeSensitive ? ' [time-sensitive]' : ''));
  });
  (res.actions || []).forEach(a=>{
    parts.push('Link offered to the user: ' + a.label + ' <' + a.url + '>');
  });
  return parts.join('\n');
}

/* askRun is the shared engine. It takes the AI layer as an argument rather
   than reaching for ASK_BACKEND / firebaseReady / appCheckReady in file scope,
   which is what previously tied the whole orchestrator to a browser.

   aiAdapter is optional and duck-typed: { ready(): boolean,
   ask(question, context): Promise<string> }. Omit it - as the WhatsApp bridge
   does - and the deterministic path runs alone, which is the same path the
   site already falls back to whenever Gemini is unavailable.

   The handler order, the halachic guard's primacy and every answer string are
   untouched by this change. */
async function askRun(question, opts, aiAdapter){
  const q = String(question || '').trim();
  if(!q) return null;
  const useAI = !(opts && opts.useAI === false);

  // Structured and CJHQ answers first: they are verifiable and need no AI.
  // Order matters: the directory guard runs before the resource matcher so a
  // community question cannot be answered with an unrelated CJHQ resource.
  // askHalachic runs FIRST. Without that, an explicitly halachic question is
  // answered by whichever practical handler matches a keyword in it, and the
  // answer reads as a ruling.
  const handlers = [askHalachic].concat(askPracticalHandlers());
  let res = null;
  for(const h of handlers){
    const out = h(q);
    if(out){ res = out; break; }
  }

  if(!res){
    // Nothing verified to ground on. Gemini is NOT called here - a model asked
    // to answer with no context is exactly how invented facts appear.
    const r = askAnswerShape();
    const L = askDetectLanguage(q); r.lang = L;
    r.handled = false; r.handler = 'none';
    r.answer = askT({
      en:'I could not match that to a CJHQ resource or a structured source, so I am not going to guess. Try the Resource Centre, or rephrase using a keyword such as passport, NEXUS, RAMQ, eruv, zmanim or Hatzolah.',
      fr:'Je n\u2019ai pas pu rattacher cela \u00e0 une ressource CJHQ ni \u00e0 une source structur\u00e9e; je ne vais donc pas deviner. Essayez le Centre de ressources, ou reformulez avec un mot-cl\u00e9 comme passeport, NEXUS, RAMQ, \u00e9rouv, zmanim ou Hatzolah.',
      he:'\u05dc\u05d0 \u05d4\u05e6\u05dc\u05d7\u05ea\u05d9 \u05dc\u05d4\u05ea\u05d0\u05d9\u05dd \u05d0\u05ea \u05d6\u05d4 \u05dc\u05de\u05e9\u05d0\u05d1 \u05e9\u05dc CJHQ \u05d0\u05d5 \u05dc\u05de\u05e7\u05d5\u05e8 \u05de\u05d5\u05d1\u05e0\u05d4, \u05dc\u05db\u05df \u05dc\u05d0 \u05d0\u05e0\u05d7\u05e9. \u05e0\u05e1\u05d5 \u05d0\u05ea \u05de\u05e8\u05db\u05d6 \u05d4\u05de\u05e9\u05d0\u05d1\u05d9\u05dd.',
      yi:'\u05d0\u05d9\u05da \u05d4\u05d0\u05d1 \u05d3\u05d0\u05e1 \u05e0\u05d9\u05e9\u05d8 \u05d2\u05e2\u05e7\u05e2\u05e0\u05d8 \u05e6\u05d5\u05e4\u05d0\u05e1\u05df \u05e6\u05d5 \u05e7\u05d9\u05d9\u05df CJHQ \u05e8\u05e2\u05e1\u05d5\u05e8\u05e1 \u05d0\u05d3\u05e2\u05e8 \u05e1\u05d8\u05e8\u05d5\u05e7\u05d8\u05d5\u05e8\u05d9\u05e8\u05d8\u05df \u05de\u05e7\u05d5\u05e8, \u05d3\u05e2\u05e8\u05d9\u05d1\u05e2\u05e8 \u05d5\u05d5\u05e2\u05dc \u05d0\u05d9\u05da \u05e0\u05d9\u05e9\u05d8 \u05d8\u05e8\u05e2\u05e4\u05df. \u05e4\u05e8\u05d5\u05d1\u05d9\u05e8\u05d8 \u05d3\u05e2\u05dd \u05e8\u05e2\u05e1\u05d5\u05e8\u05e1 \u05e6\u05e2\u05e0\u05d8\u05e2\u05e8, \u05d0\u05d3\u05e2\u05e8 \u05e9\u05e8\u05d9\u05d9\u05d1\u05d8 \u05e2\u05e1 \u05d0\u05d9\u05d1\u05e2\u05e8 \u05de\u05d9\u05d8 \u05d0 \u05d5\u05d5\u05d0\u05e8\u05d8 \u05d5\u05d5\u05d9 \u05e4\u05d0\u05e1\u05e4\u05d0\u05e8\u05d8, NEXUS, RAMQ, \u05e2\u05d9\u05e8\u05d5\u05d1, \u05d6\u05de\u05e0\u05d9\u05dd \u05d0\u05d3\u05e2\u05e8 \u05d4\u05e6\u05dc\u05d4.'
    }, L);
    r.actions = [{ label: askT({en:'CJHQ Resource Centre', fr:'Centre de ressources CJHQ', he:'\u05de\u05e8\u05db\u05d6 \u05d4\u05de\u05e9\u05d0\u05d1\u05d9\u05dd', yi:'CJHQ \u05e8\u05e2\u05e1\u05d5\u05e8\u05e1 \u05e6\u05e2\u05e0\u05d8\u05e2\u05e8'}, L), url:'/resources', kind:'internal' }];
    return r;
  }

  // A handler matched. Its answer is already correct and safe, so AI is a
  // presentation layer on top: if Gemini is unavailable, slow, throttled or
  // returns nothing usable, the deterministic answer is what the user sees.
  res.aiUsed = false;
  const aiReady = !!(aiAdapter && typeof aiAdapter.ask === 'function'
                     && (typeof aiAdapter.ready !== 'function' || aiAdapter.ready()));
  if(useAI && aiReady){
    const context = askBuildContext(res);
    if(context){
      try{
        const t0 = Date.now();
        const phrased = await aiAdapter.ask(q, context);
        res.aiLatencyMs = Date.now() - t0;
        if(phrased && phrased.length > 10){
          res.deterministicAnswer = res.answer;  // kept for admin comparison
          res.answer = phrased;
          res.aiUsed = true;
          res.aiModel = (aiAdapter && aiAdapter.model) || '';
        }
      }catch(err){
        // Never surface provider detail to a user. Quota, rate limits and
        // billing errors all look the same from outside: the assistant simply
        // answers from CJHQ's own information.
        res.aiError = String((err && err.message) || err).slice(0, 120);
        console.warn('[CJHQ] Ask CJHQ AI unavailable, using verified answer:', res.aiError);
      }
    }
  }
  return res;
}

/* Public entry point for a non-browser caller (the WhatsApp bridge). Returns
   only the fields that belong in a user-facing answer: the diagnostic fields
   askRun also sets - deterministicAnswer, aiError, aiModel, aiLatencyMs - are
   admin material and are deliberately not included. */
async function askAnswer(input){
  const opts = (input && typeof input === 'object') ? input : { text: String(input || '') };
  const text = String(opts.text || '');
  const res  = await askRun(text, { useAI: opts.useAI === true }, opts.aiAdapter);
  if(!res){
    return { answer:'', sources:[], actions:[], timeSensitive:false,
             handled:false, handler:'', lang:'en', location:'', halachic:false };
  }
  return {
    answer:        res.answer || '',
    sources:       (res.sources || []).map(s => ({ name: s.name, url: s.url || '' })),
    actions:       (res.actions || []).map(a => ({ label: a.label, url: a.url, kind: a.kind || 'link' })),
    timeSensitive: !!res.timeSensitive,
    handled:       !!res.handled,
    handler:       res.handler || '',
    lang:          res.lang || 'en',
    location:      res.location || '',
    halachic:      !!res.halachic
  };
}
/* ===== SHARED ASK CORE: END ========================================== */

export {
  askRun,
  askAnswer,
  askAnswerShape,
  askDetectLanguage,
  askDetectLocation,
  askT,
  askBuildContext,
  askMatchResources,
  askBridgeTerms,
  askSortSources,
  askPracticalHandlers,
  askHalachic,
  askEruv,
  askEmergency,
  askZmanim,
  askCalendar,
  askCommunityDirectory,
  askCjhqResources,
  cjhqNormalizeSearch
};
export { categories };
