#!/usr/bin/env python3
"""Per-page share previews for admin-created temporary pages.

Why this exists
---------------
notice.html gives every temporary page ONE generic preview card, because a
static file cannot vary its tags per ?p= value. This closes that gap: for each
currently-live custom page it writes a real static file at notice/<slug>.html
carrying that page's own og title, description and card image, so the share
link /notice/<slug> previews with the page's actual headline.

Access model: it reads Firestore over the public REST API with the same
publishable web apiKey the site's own JavaScript uses - no credentials, no
admin access. The security rules already decide what is public: a page that is
unpublished, not yet started or expired answers permission-denied, exactly as
it does for an anonymous visitor, and no file is written for it. Files for
pages that have left the live window are deleted on the next run.

Safety: if the index document cannot be read the script exits non-zero WITHOUT
touching the working tree, so a Firestore outage can never wipe the generated
files. Deletions only ever follow a successful index read.

Runs on the GitHub Action in .github/workflows/notice-pages.yml (hourly plus
manual dispatch); can also be run locally with `pip install pillow`.

    python3 tools/generate-notice-pages.py
"""
import html, json, os, re, shutil, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT = 'cjhqinfo'
API_KEY = 'AIzaSyDPzTFbsiOtJ4LOKiFjL0aVtSKhl21zwuc'  # public web key, same as index.html
BASE = f'https://firestore.googleapis.com/v1/projects/{PROJECT}/databases/(default)/documents'
ORIGIN = 'https://cjhq.org'
SLUG_RE = re.compile(r'^[a-z0-9][a-z0-9-]{0,60}$')


def get(path):
    req = urllib.request.Request(f'{BASE}/{path}?key={API_KEY}',
                                 headers={'User-Agent': 'cjhq-notice-pages/1.0'})
    with urllib.request.urlopen(req, timeout=20) as r:
        return json.load(r)


def field(doc, name, default=''):
    v = doc.get('fields', {}).get(name, {})
    return v.get('stringValue', default)


def strip_html(s):
    s = re.sub(r'<[^>]+>', ' ', s or '')
    return re.sub(r'\s+', ' ', html.unescape(s)).strip()


def make_card(en_short, fr_short, out_path):
    """Same classic treatment as the static pages' cards: og-cards.py's build()
       (logo lockup + footer strip lifted from og-image.png, Lora labels)."""
    import importlib.util
    spec = importlib.util.spec_from_file_location(
        'ogcards', os.path.join(ROOT, 'tools', 'og-cards.py'))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    m.build(en_short, fr_short, out_path)


HTML_TMPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- GENERATED by tools/generate-notice-pages.py - do not edit by hand.
     Per-page share preview for the temporary page "{slug}" (served at both
     /notice/{slug} and the direct address /{slug}). The crawler reads
     the tags below straight out of this static file; a human visitor is
     forwarded to the page itself through the site's own router, which enforces
     the publish window and shows the normal 404 outside it. Deleted
     automatically when the page leaves its live window. -->
<title>{title}</title>
<meta name="description" content="{desc}">
<link rel="canonical" href="{origin}/{slug}">
<meta name="robots" content="noindex, follow">
<meta property="og:type" content="article">
<meta property="og:site_name" content="CJHQ">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta property="og:url" content="{origin}/{slug}">
<meta property="og:image" content="{origin}/assets/og-notice-{slug}.png">
<meta property="og:image:secure_url" content="{origin}/assets/og-notice-{slug}.png">
<meta property="og:image:type" content="image/png">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="{title} — CJHQ">
<meta property="og:locale" content="en_CA">
<meta property="og:locale:alternate" content="fr_CA">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="{origin}/assets/og-notice-{slug}.png">
<link rel="icon" href="/favicon.ico">
<style>
  body{{margin:0;font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;
       color:#0E2149;background:#fff;display:flex;min-height:100vh;align-items:center;
       justify-content:center;padding:24px;}}
  .box{{max-width:30rem;text-align:center;}}
  h1{{font-size:1.15rem;font-weight:600;margin:0 0 8px;}}
  a{{color:#0E2149;}}
</style>
<script>
  (function(){{
    var base = '/';
    try{{
      base = location.pathname.replace(/\/(notice\/)?[a-z0-9-]+(\.html|\/index\.html)?\/?$/i, '') + '/';
      location.replace(base + '{target}');
    }}catch(e){{ location.replace(base); }}
  }})();
</script>
</head>
<body>
  <div class="box">
    <h1>{title_h1}</h1>
    <p>Opening the notice… <a href="/">Go to cjhq.org</a> if nothing happens.</p>
  </div>
</body>
</html>
"""


MARKER = 'GENERATED by tools/generate-notice-pages.py'


def _js_json(obj):
    """JSON safe to drop inside an inline <script>."""
    s = json.dumps(obj, ensure_ascii=False)
    return (s.replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
             .replace('\u2028', '\\u2028').replace('\u2029', '\\u2029'))


def bake_page(slug, doc, title, desc):
    """The full site (index.html) with this notice already on screen.

    The visitor gets the page itself at /<slug>/ - no bounce through the
    homepage, no wait on Firestore. The body is still sanitised by DOMPurify in
    the browser exactly like the live render (loaded synchronously on this page
    only), and the site's router still checks Firestore afterwards, so a page
    that has been unpublished or has expired turns into the normal 404 even
    before the next run deletes this file. Returns None if index.html no longer
    matches the expected shape - the caller then falls back to the redirect
    stub, so a site change can never break a notice link."""
    try:
        src = open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read()
    except OSError:
        return None
    e = lambda v: html.escape(v, quote=True)
    url = f'{ORIGIN}/{slug}'
    img = f'{ORIGIN}/assets/og-notice-{slug}.png'
    subs = [
        (r'<title id="pageTitle">[^<]*</title>', f'<title id="pageTitle">{e(title)}</title>'),
        (r'<meta name="description" content="[^"]*">', f'<meta name="description" content="{e(desc)}">'),
        (r'<meta name="robots" content="[^"]*">', '<meta name="robots" content="noindex, follow">'),
        (r'<link rel="canonical" id="canonicalTag" href="[^"]*">', f'<link rel="canonical" id="canonicalTag" href="{url}">'),
        (r'<meta property="og:type" content="[^"]*">', '<meta property="og:type" content="article">'),
        (r'<meta property="og:title" id="ogTitle" content="[^"]*">', f'<meta property="og:title" id="ogTitle" content="{e(title)}">'),
        (r'<meta property="og:description" id="ogDescription" content="[^"]*">', f'<meta property="og:description" id="ogDescription" content="{e(desc)}">'),
        (r'<meta property="og:url" id="ogUrl" content="[^"]*">', f'<meta property="og:url" id="ogUrl" content="{url}">'),
        (r'<meta property="og:image" id="ogImage" content="[^"]*">', f'<meta property="og:image" id="ogImage" content="{img}">'),
        (r'<meta property="og:image:alt" id="ogImageAlt" content="[^"]*">', f'<meta property="og:image:alt" id="ogImageAlt" content="{e(title)} — CJHQ">'),
        (r'<meta name="twitter:title" id="twitterTitle" content="[^"]*">', f'<meta name="twitter:title" id="twitterTitle" content="{e(title)}">'),
        (r'<meta name="twitter:description" id="twitterDescription" content="[^"]*">', f'<meta name="twitter:description" id="twitterDescription" content="{e(desc)}">'),
        (r'<meta name="twitter:image" id="twitterImage" content="[^"]*">', f'<meta name="twitter:image" id="twitterImage" content="{img}">'),
        (r'<script defer src="/assets/purify\.min\.js"></script>', '<script src="/assets/purify.min.js"></script>'),
        (r'<div class="page active" id="page-home">', '<div class="page" id="page-home">'),
        (r'<div class="page" id="page-custom">', '<div class="page active" id="page-custom">'),
    ]
    for pat, rep in subs:
        src, n = re.subn(pat, lambda m, r=rep: r, src, count=1)
        if n != 1:
            return None
    # hreflang alternates point at the homepage; they do not apply here.
    src = re.sub(r'<link rel="alternate" hreflang="[^"]*" href="[^"]*">\n?', '', src)
    data = {'slug': slug, 'title_en': field(doc, 'title_en'), 'title_fr': field(doc, 'title_fr'),
            'body_en': field(doc, 'body_en'), 'body_fr': field(doc, 'body_fr'),
            'body_format': field(doc, 'body_format') or None}
    t_en, t_fr = html.escape(data['title_en']), html.escape(data['title_fr'])
    title_html = f'<span data-en>{t_en}</span><span data-fr>{t_fr}</span>'
    render = ('<script>\n'
              f'window.__CJHQ_PRERENDER = {_js_json(data)};\n'
              '(function(p){\n'
              '  function esc(v){ return String(v == null ? "" : v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/\'/g,"&#39;"); }\n'
              '  function body(b){ b = String(b == null ? "" : b);\n'
              '    if(p.body_format !== "text"){ return (window.DOMPurify && DOMPurify.sanitize) ? DOMPurify.sanitize(b) : esc(b); }\n'
              '    return b.replace(/\\r\\n?/g, "\\n").split(/\\n{2,}/).map(function(x){ return x.trim(); }).filter(Boolean)\n'
              '      .map(function(x){ return "<p>" + esc(x).replace(/\\n/g, "<br>") + "</p>"; }).join(""); }\n'
              '  document.getElementById("customPageBody").innerHTML =\n'
              '    "<div data-en>" + body(p.body_en) + "</div><div data-fr>" + body(p.body_fr || p.body_en) + "</div>";\n'
              '})(window.__CJHQ_PRERENDER);\n'
              '</script>')
    pat = re.compile(r'(<h1 id="customPageTitle"[^>]*>)(</h1>\s*<div id="customPageBody"[^>]*>)(</div>)')
    m = pat.search(src)
    if not m:
        return None
    src = src[:m.start()] + m.group(1) + title_html + m.group(2) + m.group(3) + '\n' + render + src[m.end():]
    note = (f'<!-- {MARKER} - do not edit by hand. Baked copy of index.html with the '
            f'temporary page "{slug}" already rendered; rewritten every run, deleted '
            'when the page leaves its live window. -->\n')
    return src.replace('<head>', '<head>\n' + note, 1)


def main():
    try:
        idx = get('page_settings/public_pages')
    except Exception as e:
        sys.exit(f'public_pages index unreadable ({e}) - leaving the tree untouched.')
    raw = idx.get('fields', {}).get('slugs', {}).get('arrayValue', {}).get('values', [])
    slugs = []
    for v in raw:
        s = v.get('stringValue', '').strip().lower()
        if SLUG_RE.match(s) and s not in slugs:
            slugs.append(s)

    notice_dir = os.path.join(ROOT, 'notice')
    os.makedirs(notice_dir, exist_ok=True)
    live, skipped, collisions = [], [], []
    for slug in slugs:
        try:
            doc = get(f'custom_pages/{slug}')
        except Exception:
            skipped.append(slug)  # outside its window or unpublished: rules deny, so no file
            continue
        title = field(doc, 'title_en') or 'CJHQ Community Notice'
        body_txt = strip_html(field(doc, 'body_en'))
        if title and body_txt.lower().startswith(title.lower()):
            body_txt = body_txt[len(title):].lstrip(' .·')
        desc = field(doc, 'home_blurb_en') or body_txt[:160] \
               or 'Official community information and updates from the Jewish Hasidic Council of Quebec.'
        short = title.split('·')[0].strip() or 'CJHQ Community Notice'
        page_html = HTML_TMPL.format(slug=slug, origin=ORIGIN, target=slug + '/',
                                     title=html.escape(title, quote=True),
                                     title_h1=html.escape(title),
                                     desc=html.escape(desc, quote=True))
        # notice/<slug>.html stays a light preview-card stub that forwards to
        # the baked page; the direct address gets the full baked page.
        with open(os.path.join(notice_dir, f'{slug}.html'), 'w', encoding='utf-8') as f:
            f.write(page_html)
        # Fallback if index.html changed shape: the old stub that bridges into
        # the SPA (never the /<slug>/ target, which would loop onto itself).
        baked = bake_page(slug, doc, title, desc) or HTML_TMPL.format(
            slug=slug, origin=ORIGIN, target='?/' + slug,
            title=html.escape(title, quote=True), title_h1=html.escape(title),
            desc=html.escape(desc, quote=True))
        # The direct address /<slug> is the link people actually type and
        # share; give it the same preview file. Guard against colliding with
        # a real site route (about.html, fr/, ...) or a hand-made directory:
        # only a directory whose index.html carries our marker is ours.
        direct_dir = os.path.join(ROOT, slug)
        marker = MARKER
        direct_index = os.path.join(direct_dir, 'index.html')
        direct_html = os.path.join(ROOT, f'{slug}.html')
        if (os.path.exists(direct_html)
               and marker not in open(direct_html, encoding='utf-8', errors='ignore').read(4096)) \
           or (os.path.isdir(direct_dir) \
               and not (os.path.isfile(direct_index) and marker in open(direct_index, encoding='utf-8', errors='ignore').read(4096))):
            collisions.append(slug)
        else:
            os.makedirs(direct_dir, exist_ok=True)
            with open(direct_index, 'w', encoding='utf-8') as f:
                f.write(baked)
            # /<slug>.html lets GitHub Pages answer /<slug> directly, without
            # the 301 to /<slug>/ that a directory alone gets.
            with open(direct_html, 'w', encoding='utf-8') as f:
                f.write(baked)
        fr_short = (field(doc, 'title_fr').split('\u00b7')[0].strip()
                    or 'AVIS COMMUNAUTAIRE').upper()
        if fr_short == short.upper():
            fr_short = ''  # identical EN/FR titles: one line is enough
        make_card(short.upper(), fr_short,
                  os.path.join(ROOT, 'assets', f'og-notice-{slug}.png'))
        live.append(slug)

    # Remove generated files for pages that left the live window.
    removed = []
    for name in os.listdir(notice_dir):
        m = re.fullmatch(r'([a-z0-9][a-z0-9-]{0,60})\.html', name)
        if m and m.group(1) not in live:
            os.remove(os.path.join(notice_dir, name)); removed.append(name)
    marker = 'GENERATED by tools/generate-notice-pages.py'
    for name in os.listdir(ROOT):
        d = os.path.join(ROOT, name)
        idx = os.path.join(d, 'index.html')
        if (os.path.isdir(d) and re.fullmatch(r'[a-z0-9][a-z0-9-]{0,60}', name)
                and name not in live and os.path.isfile(idx)
                and marker in open(idx, encoding='utf-8', errors='ignore').read(4096)):
            shutil.rmtree(d); removed.append(name + '/')
    for name in os.listdir(ROOT):
        m = re.fullmatch(r'([a-z0-9][a-z0-9-]{0,60})\.html', name)
        p = os.path.join(ROOT, name)
        if (m and m.group(1) not in live and os.path.isfile(p)
                and marker in open(p, encoding='utf-8', errors='ignore').read(4096)):
            os.remove(p); removed.append(name)
    assets = os.path.join(ROOT, 'assets')
    for name in os.listdir(assets):
        m = re.fullmatch(r'og-notice-([a-z0-9][a-z0-9-]{0,60})\.png', name)
        if m and m.group(1) not in live and m.group(1) not in ('v1', 'v2'):
            os.remove(os.path.join(assets, name)); removed.append(name)

    print(f'live: {live or "none"}  skipped(not public): {skipped or "none"}  removed: {removed or "none"}  collisions: {collisions or "none"}')


if __name__ == '__main__':
    main()
